// <auto-generated />
#nullable enable

namespace Enyim.Iris.Protocol
{
  /// <summary>A domain for ad-related metrics and data.</summary>
  public static partial class Ads
  {
    /// <summary>Ad metrics for a page.</summary>
    /// <param name="ViewportAdDensityByArea">
    /// The viewport ad density by area, represented as a percentage (an integer<br/>
    /// between 0 and 100).<br/>
    /// </param>
    /// <param name="AverageViewportAdDensityByArea">
    /// The time-weighted average of the viewport ad density by area, measured<br/>
    /// across the duration of the page.<br/>
    /// </param>
    /// <param name="ViewportAdCount">The number of ads currently visible within the viewport.</param>
    /// <param name="AverageViewportAdCount">
    /// The time-weighted average of the viewport ad count, measured across the<br/>
    /// duration of the page.<br/>
    /// </param>
    /// <param name="TotalAdCpuTime">The total ad CPU usage, in milliseconds.</param>
    /// <param name="TotalAdNetworkBytes">The total ad network bytes.</param>
    public record AdMetricsType(
      [property: System.Text.Json.Serialization.JsonPropertyName("viewportAdDensityByArea")]
      int ViewportAdDensityByArea,
      [property: System.Text.Json.Serialization.JsonPropertyName("averageViewportAdDensityByArea")]
      double AverageViewportAdDensityByArea,
      [property: System.Text.Json.Serialization.JsonPropertyName("viewportAdCount")]
      int ViewportAdCount,
      [property: System.Text.Json.Serialization.JsonPropertyName("averageViewportAdCount")]
      double AverageViewportAdCount,
      [property: System.Text.Json.Serialization.JsonPropertyName("totalAdCpuTime")]
      double TotalAdCpuTime,
      [property: System.Text.Json.Serialization.JsonPropertyName("totalAdNetworkBytes")]
      double TotalAdNetworkBytes
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Retrieves ad metrics for the current page.</summary>
    public static Enyim.Iris.Protocol.Ads.GetAdMetricsRequest GetAdMetrics()    
    {
      return new Enyim.Iris.Protocol.Ads.GetAdMetricsRequest();
    }
    /// <summary>Retrieves ad metrics for the current page.</summary>
    [ChromeProtocol.Core.MethodName("Ads.getAdMetrics")]
    public record GetAdMetricsRequest() : ChromeProtocol.Core.ICommand<GetAdMetricsRequestResult>
    {
    }
    public record GetAdMetricsRequestResult(
      [property: System.Text.Json.Serialization.JsonPropertyName("metrics")]
      Enyim.Iris.Protocol.Ads.AdMetricsType Metrics
    ) : ChromeProtocol.Core.IType
    {
    }
  }
}
