// <auto-generated />
#nullable enable

namespace Enyim.Iris.Protocol
{
  /// <summary>
  /// This domain allows configuring virtual Bluetooth devices to test<br/>
  /// the web-bluetooth API.<br/>
  /// </summary>
  public static partial class BluetoothEmulation
  {
    /// <summary>Indicates the various states of Central.</summary>
    [System.Text.Json.Serialization.JsonConverter(typeof(ChromeProtocol.Core.PrimitiveTypeConverter))]
    public record CentralStateType(
      string Value
    ) : ChromeProtocol.Core.PrimitiveType<string>(Value)
    {
    }
    /// <summary>Indicates the various types of GATT event.</summary>
    [System.Text.Json.Serialization.JsonConverter(typeof(ChromeProtocol.Core.PrimitiveTypeConverter))]
    public record GATTOperationTypeType(
      string Value
    ) : ChromeProtocol.Core.PrimitiveType<string>(Value)
    {
    }
    /// <summary>Indicates the various types of characteristic write.</summary>
    [System.Text.Json.Serialization.JsonConverter(typeof(ChromeProtocol.Core.PrimitiveTypeConverter))]
    public record CharacteristicWriteTypeType(
      string Value
    ) : ChromeProtocol.Core.PrimitiveType<string>(Value)
    {
    }
    /// <summary>Indicates the various types of characteristic operation.</summary>
    [System.Text.Json.Serialization.JsonConverter(typeof(ChromeProtocol.Core.PrimitiveTypeConverter))]
    public record CharacteristicOperationTypeType(
      string Value
    ) : ChromeProtocol.Core.PrimitiveType<string>(Value)
    {
    }
    /// <summary>Indicates the various types of descriptor operation.</summary>
    [System.Text.Json.Serialization.JsonConverter(typeof(ChromeProtocol.Core.PrimitiveTypeConverter))]
    public record DescriptorOperationTypeType(
      string Value
    ) : ChromeProtocol.Core.PrimitiveType<string>(Value)
    {
    }
    /// <summary>Stores the manufacturer data</summary>
    /// <param name="Key">
    /// Company identifier<br/>
    /// https://bitbucket.org/bluetooth-SIG/public/src/main/assigned_numbers/company_identifiers/company_identifiers.yaml<br/>
    /// https://usb.org/developers<br/>
    /// </param>
    /// <param name="Data">Manufacturer-specific data (Encoded as a base64 string when passed over JSON)</param>
    public record ManufacturerDataType(
      [property: System.Text.Json.Serialization.JsonPropertyName("key")]
      int Key,
      [property: System.Text.Json.Serialization.JsonPropertyName("data")]
      string Data
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Stores the byte data of the advertisement packet sent by a Bluetooth device.</summary>
    /// <param name="Appearance">Stores the external appearance description of the device.</param>
    /// <param name="TxPower">Stores the transmission power of a broadcasting device.</param>
    /// <param name="ManufacturerData">
    /// Key is the company identifier and the value is an array of bytes of<br/>
    /// manufacturer specific data.<br/>
    /// </param>
    public record ScanRecordType(
      [property: System.Text.Json.Serialization.JsonPropertyName("name")]
      string? Name = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("uuids")]
      System.Collections.Generic.IReadOnlyList<string>? Uuids = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("appearance")]
      int? Appearance = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("txPower")]
      int? TxPower = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("manufacturerData")]
      System.Collections.Generic.IReadOnlyList<Enyim.Iris.Protocol.BluetoothEmulation.ManufacturerDataType>? ManufacturerData = default
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Stores the advertisement packet information that is sent by a Bluetooth device.</summary>
    public record ScanEntryType(
      [property: System.Text.Json.Serialization.JsonPropertyName("deviceAddress")]
      string DeviceAddress,
      [property: System.Text.Json.Serialization.JsonPropertyName("rssi")]
      int Rssi,
      [property: System.Text.Json.Serialization.JsonPropertyName("scanRecord")]
      Enyim.Iris.Protocol.BluetoothEmulation.ScanRecordType ScanRecord
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Describes the properties of a characteristic. This follows Bluetooth Core<br/>
    /// Specification BT 4.2 Vol 3 Part G 3.3.1. Characteristic Properties.<br/>
    /// </summary>
    public record CharacteristicPropertiesType(
      [property: System.Text.Json.Serialization.JsonPropertyName("broadcast")]
      bool? Broadcast = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("read")]
      bool? Read = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("writeWithoutResponse")]
      bool? WriteWithoutResponse = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("write")]
      bool? Write = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("notify")]
      bool? Notify = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("indicate")]
      bool? Indicate = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("authenticatedSignedWrites")]
      bool? AuthenticatedSignedWrites = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("extendedProperties")]
      bool? ExtendedProperties = default
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Event for when a GATT operation of |type| to the peripheral with |address|<br/>
    /// happened.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("BluetoothEmulation.gattOperationReceived")]
    public record GattOperationReceived(
      [property: System.Text.Json.Serialization.JsonPropertyName("address")]
      string Address,
      [property: System.Text.Json.Serialization.JsonPropertyName("type")]
      Enyim.Iris.Protocol.BluetoothEmulation.GATTOperationTypeType Type
    ) : ChromeProtocol.Core.IEvent
    {
    }
    /// <summary>
    /// Event for when a characteristic operation of |type| to the characteristic<br/>
    /// respresented by |characteristicId| happened. |data| and |writeType| is<br/>
    /// expected to exist when |type| is write.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("BluetoothEmulation.characteristicOperationReceived")]
    public record CharacteristicOperationReceived(
      [property: System.Text.Json.Serialization.JsonPropertyName("characteristicId")]
      string CharacteristicId,
      [property: System.Text.Json.Serialization.JsonPropertyName("type")]
      Enyim.Iris.Protocol.BluetoothEmulation.CharacteristicOperationTypeType Type,
      [property: System.Text.Json.Serialization.JsonPropertyName("data")]
      string? Data = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("writeType")]
      Enyim.Iris.Protocol.BluetoothEmulation.CharacteristicWriteTypeType? WriteType = default
    ) : ChromeProtocol.Core.IEvent
    {
    }
    /// <summary>
    /// Event for when a descriptor operation of |type| to the descriptor<br/>
    /// respresented by |descriptorId| happened. |data| is expected to exist when<br/>
    /// |type| is write.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("BluetoothEmulation.descriptorOperationReceived")]
    public record DescriptorOperationReceived(
      [property: System.Text.Json.Serialization.JsonPropertyName("descriptorId")]
      string DescriptorId,
      [property: System.Text.Json.Serialization.JsonPropertyName("type")]
      Enyim.Iris.Protocol.BluetoothEmulation.DescriptorOperationTypeType Type,
      [property: System.Text.Json.Serialization.JsonPropertyName("data")]
      string? Data = default
    ) : ChromeProtocol.Core.IEvent
    {
    }
    /// <summary>Enable the BluetoothEmulation domain.</summary>
    /// <param name="State">State of the simulated central.</param>
    /// <param name="LeSupported">If the simulated central supports low-energy.</param>
    public static Enyim.Iris.Protocol.BluetoothEmulation.EnableRequest Enable(Enyim.Iris.Protocol.BluetoothEmulation.CentralStateType State, bool LeSupported)    
    {
      return new Enyim.Iris.Protocol.BluetoothEmulation.EnableRequest(State, LeSupported);
    }
    /// <summary>Enable the BluetoothEmulation domain.</summary>
    /// <param name="State">State of the simulated central.</param>
    /// <param name="LeSupported">If the simulated central supports low-energy.</param>
    [ChromeProtocol.Core.MethodName("BluetoothEmulation.enable")]
    public record EnableRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("state")]
      Enyim.Iris.Protocol.BluetoothEmulation.CentralStateType State,
      [property: System.Text.Json.Serialization.JsonPropertyName("leSupported")]
      bool LeSupported
    ) : ChromeProtocol.Core.ICommand<EnableRequestResult>
    {
    }
    public record EnableRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Set the state of the simulated central.</summary>
    /// <param name="State">State of the simulated central.</param>
    public static Enyim.Iris.Protocol.BluetoothEmulation.SetSimulatedCentralStateRequest SetSimulatedCentralState(Enyim.Iris.Protocol.BluetoothEmulation.CentralStateType State)    
    {
      return new Enyim.Iris.Protocol.BluetoothEmulation.SetSimulatedCentralStateRequest(State);
    }
    /// <summary>Set the state of the simulated central.</summary>
    /// <param name="State">State of the simulated central.</param>
    [ChromeProtocol.Core.MethodName("BluetoothEmulation.setSimulatedCentralState")]
    public record SetSimulatedCentralStateRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("state")]
      Enyim.Iris.Protocol.BluetoothEmulation.CentralStateType State
    ) : ChromeProtocol.Core.ICommand<SetSimulatedCentralStateRequestResult>
    {
    }
    public record SetSimulatedCentralStateRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Disable the BluetoothEmulation domain.</summary>
    public static Enyim.Iris.Protocol.BluetoothEmulation.DisableRequest Disable()    
    {
      return new Enyim.Iris.Protocol.BluetoothEmulation.DisableRequest();
    }
    /// <summary>Disable the BluetoothEmulation domain.</summary>
    [ChromeProtocol.Core.MethodName("BluetoothEmulation.disable")]
    public record DisableRequest() : ChromeProtocol.Core.ICommand<DisableRequestResult>
    {
    }
    public record DisableRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Simulates a peripheral with |address|, |name| and |knownServiceUuids|<br/>
    /// that has already been connected to the system.<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.BluetoothEmulation.SimulatePreconnectedPeripheralRequest SimulatePreconnectedPeripheral(string Address, string Name, System.Collections.Generic.IReadOnlyList<Enyim.Iris.Protocol.BluetoothEmulation.ManufacturerDataType> ManufacturerData, System.Collections.Generic.IReadOnlyList<string> KnownServiceUuids)    
    {
      return new Enyim.Iris.Protocol.BluetoothEmulation.SimulatePreconnectedPeripheralRequest(Address, Name, ManufacturerData, KnownServiceUuids);
    }
    /// <summary>
    /// Simulates a peripheral with |address|, |name| and |knownServiceUuids|<br/>
    /// that has already been connected to the system.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("BluetoothEmulation.simulatePreconnectedPeripheral")]
    public record SimulatePreconnectedPeripheralRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("address")]
      string Address,
      [property: System.Text.Json.Serialization.JsonPropertyName("name")]
      string Name,
      [property: System.Text.Json.Serialization.JsonPropertyName("manufacturerData")]
      System.Collections.Generic.IReadOnlyList<Enyim.Iris.Protocol.BluetoothEmulation.ManufacturerDataType> ManufacturerData,
      [property: System.Text.Json.Serialization.JsonPropertyName("knownServiceUuids")]
      System.Collections.Generic.IReadOnlyList<string> KnownServiceUuids
    ) : ChromeProtocol.Core.ICommand<SimulatePreconnectedPeripheralRequestResult>
    {
    }
    public record SimulatePreconnectedPeripheralRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Simulates an advertisement packet described in |entry| being received by<br/>
    /// the central.<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.BluetoothEmulation.SimulateAdvertisementRequest SimulateAdvertisement(Enyim.Iris.Protocol.BluetoothEmulation.ScanEntryType Entry)    
    {
      return new Enyim.Iris.Protocol.BluetoothEmulation.SimulateAdvertisementRequest(Entry);
    }
    /// <summary>
    /// Simulates an advertisement packet described in |entry| being received by<br/>
    /// the central.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("BluetoothEmulation.simulateAdvertisement")]
    public record SimulateAdvertisementRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("entry")]
      Enyim.Iris.Protocol.BluetoothEmulation.ScanEntryType Entry
    ) : ChromeProtocol.Core.ICommand<SimulateAdvertisementRequestResult>
    {
    }
    public record SimulateAdvertisementRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Simulates the response code from the peripheral with |address| for a<br/>
    /// GATT operation of |type|. The |code| value follows the HCI Error Codes from<br/>
    /// Bluetooth Core Specification Vol 2 Part D 1.3 List Of Error Codes.<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.BluetoothEmulation.SimulateGATTOperationResponseRequest SimulateGATTOperationResponse(string Address, Enyim.Iris.Protocol.BluetoothEmulation.GATTOperationTypeType Type, int Code)    
    {
      return new Enyim.Iris.Protocol.BluetoothEmulation.SimulateGATTOperationResponseRequest(Address, Type, Code);
    }
    /// <summary>
    /// Simulates the response code from the peripheral with |address| for a<br/>
    /// GATT operation of |type|. The |code| value follows the HCI Error Codes from<br/>
    /// Bluetooth Core Specification Vol 2 Part D 1.3 List Of Error Codes.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("BluetoothEmulation.simulateGATTOperationResponse")]
    public record SimulateGATTOperationResponseRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("address")]
      string Address,
      [property: System.Text.Json.Serialization.JsonPropertyName("type")]
      Enyim.Iris.Protocol.BluetoothEmulation.GATTOperationTypeType Type,
      [property: System.Text.Json.Serialization.JsonPropertyName("code")]
      int Code
    ) : ChromeProtocol.Core.ICommand<SimulateGATTOperationResponseRequestResult>
    {
    }
    public record SimulateGATTOperationResponseRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Simulates the response from the characteristic with |characteristicId| for a<br/>
    /// characteristic operation of |type|. The |code| value follows the Error<br/>
    /// Codes from Bluetooth Core Specification Vol 3 Part F 3.4.1.1 Error Response.<br/>
    /// The |data| is expected to exist when simulating a successful read operation<br/>
    /// response.<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.BluetoothEmulation.SimulateCharacteristicOperationResponseRequest SimulateCharacteristicOperationResponse(string CharacteristicId, Enyim.Iris.Protocol.BluetoothEmulation.CharacteristicOperationTypeType Type, int Code, string? Data = default)    
    {
      return new Enyim.Iris.Protocol.BluetoothEmulation.SimulateCharacteristicOperationResponseRequest(CharacteristicId, Type, Code, Data);
    }
    /// <summary>
    /// Simulates the response from the characteristic with |characteristicId| for a<br/>
    /// characteristic operation of |type|. The |code| value follows the Error<br/>
    /// Codes from Bluetooth Core Specification Vol 3 Part F 3.4.1.1 Error Response.<br/>
    /// The |data| is expected to exist when simulating a successful read operation<br/>
    /// response.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("BluetoothEmulation.simulateCharacteristicOperationResponse")]
    public record SimulateCharacteristicOperationResponseRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("characteristicId")]
      string CharacteristicId,
      [property: System.Text.Json.Serialization.JsonPropertyName("type")]
      Enyim.Iris.Protocol.BluetoothEmulation.CharacteristicOperationTypeType Type,
      [property: System.Text.Json.Serialization.JsonPropertyName("code")]
      int Code,
      [property: System.Text.Json.Serialization.JsonPropertyName("data")]
      string? Data = default
    ) : ChromeProtocol.Core.ICommand<SimulateCharacteristicOperationResponseRequestResult>
    {
    }
    public record SimulateCharacteristicOperationResponseRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Simulates the response from the descriptor with |descriptorId| for a<br/>
    /// descriptor operation of |type|. The |code| value follows the Error<br/>
    /// Codes from Bluetooth Core Specification Vol 3 Part F 3.4.1.1 Error Response.<br/>
    /// The |data| is expected to exist when simulating a successful read operation<br/>
    /// response.<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.BluetoothEmulation.SimulateDescriptorOperationResponseRequest SimulateDescriptorOperationResponse(string DescriptorId, Enyim.Iris.Protocol.BluetoothEmulation.DescriptorOperationTypeType Type, int Code, string? Data = default)    
    {
      return new Enyim.Iris.Protocol.BluetoothEmulation.SimulateDescriptorOperationResponseRequest(DescriptorId, Type, Code, Data);
    }
    /// <summary>
    /// Simulates the response from the descriptor with |descriptorId| for a<br/>
    /// descriptor operation of |type|. The |code| value follows the Error<br/>
    /// Codes from Bluetooth Core Specification Vol 3 Part F 3.4.1.1 Error Response.<br/>
    /// The |data| is expected to exist when simulating a successful read operation<br/>
    /// response.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("BluetoothEmulation.simulateDescriptorOperationResponse")]
    public record SimulateDescriptorOperationResponseRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("descriptorId")]
      string DescriptorId,
      [property: System.Text.Json.Serialization.JsonPropertyName("type")]
      Enyim.Iris.Protocol.BluetoothEmulation.DescriptorOperationTypeType Type,
      [property: System.Text.Json.Serialization.JsonPropertyName("code")]
      int Code,
      [property: System.Text.Json.Serialization.JsonPropertyName("data")]
      string? Data = default
    ) : ChromeProtocol.Core.ICommand<SimulateDescriptorOperationResponseRequestResult>
    {
    }
    public record SimulateDescriptorOperationResponseRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Adds a service with |serviceUuid| to the peripheral with |address|.</summary>
    public static Enyim.Iris.Protocol.BluetoothEmulation.AddServiceRequest AddService(string Address, string ServiceUuid)    
    {
      return new Enyim.Iris.Protocol.BluetoothEmulation.AddServiceRequest(Address, ServiceUuid);
    }
    /// <summary>Adds a service with |serviceUuid| to the peripheral with |address|.</summary>
    [ChromeProtocol.Core.MethodName("BluetoothEmulation.addService")]
    public record AddServiceRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("address")]
      string Address,
      [property: System.Text.Json.Serialization.JsonPropertyName("serviceUuid")]
      string ServiceUuid
    ) : ChromeProtocol.Core.ICommand<AddServiceRequestResult>
    {
    }
    /// <param name="ServiceId">An identifier that uniquely represents this service.</param>
    public record AddServiceRequestResult(
      [property: System.Text.Json.Serialization.JsonPropertyName("serviceId")]
      string ServiceId
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Removes the service respresented by |serviceId| from the simulated central.</summary>
    public static Enyim.Iris.Protocol.BluetoothEmulation.RemoveServiceRequest RemoveService(string ServiceId)    
    {
      return new Enyim.Iris.Protocol.BluetoothEmulation.RemoveServiceRequest(ServiceId);
    }
    /// <summary>Removes the service respresented by |serviceId| from the simulated central.</summary>
    [ChromeProtocol.Core.MethodName("BluetoothEmulation.removeService")]
    public record RemoveServiceRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("serviceId")]
      string ServiceId
    ) : ChromeProtocol.Core.ICommand<RemoveServiceRequestResult>
    {
    }
    public record RemoveServiceRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Adds a characteristic with |characteristicUuid| and |properties| to the<br/>
    /// service represented by |serviceId|.<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.BluetoothEmulation.AddCharacteristicRequest AddCharacteristic(string ServiceId, string CharacteristicUuid, Enyim.Iris.Protocol.BluetoothEmulation.CharacteristicPropertiesType Properties)    
    {
      return new Enyim.Iris.Protocol.BluetoothEmulation.AddCharacteristicRequest(ServiceId, CharacteristicUuid, Properties);
    }
    /// <summary>
    /// Adds a characteristic with |characteristicUuid| and |properties| to the<br/>
    /// service represented by |serviceId|.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("BluetoothEmulation.addCharacteristic")]
    public record AddCharacteristicRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("serviceId")]
      string ServiceId,
      [property: System.Text.Json.Serialization.JsonPropertyName("characteristicUuid")]
      string CharacteristicUuid,
      [property: System.Text.Json.Serialization.JsonPropertyName("properties")]
      Enyim.Iris.Protocol.BluetoothEmulation.CharacteristicPropertiesType Properties
    ) : ChromeProtocol.Core.ICommand<AddCharacteristicRequestResult>
    {
    }
    /// <param name="CharacteristicId">An identifier that uniquely represents this characteristic.</param>
    public record AddCharacteristicRequestResult(
      [property: System.Text.Json.Serialization.JsonPropertyName("characteristicId")]
      string CharacteristicId
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Removes the characteristic respresented by |characteristicId| from the<br/>
    /// simulated central.<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.BluetoothEmulation.RemoveCharacteristicRequest RemoveCharacteristic(string CharacteristicId)    
    {
      return new Enyim.Iris.Protocol.BluetoothEmulation.RemoveCharacteristicRequest(CharacteristicId);
    }
    /// <summary>
    /// Removes the characteristic respresented by |characteristicId| from the<br/>
    /// simulated central.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("BluetoothEmulation.removeCharacteristic")]
    public record RemoveCharacteristicRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("characteristicId")]
      string CharacteristicId
    ) : ChromeProtocol.Core.ICommand<RemoveCharacteristicRequestResult>
    {
    }
    public record RemoveCharacteristicRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Adds a descriptor with |descriptorUuid| to the characteristic respresented<br/>
    /// by |characteristicId|.<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.BluetoothEmulation.AddDescriptorRequest AddDescriptor(string CharacteristicId, string DescriptorUuid)    
    {
      return new Enyim.Iris.Protocol.BluetoothEmulation.AddDescriptorRequest(CharacteristicId, DescriptorUuid);
    }
    /// <summary>
    /// Adds a descriptor with |descriptorUuid| to the characteristic respresented<br/>
    /// by |characteristicId|.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("BluetoothEmulation.addDescriptor")]
    public record AddDescriptorRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("characteristicId")]
      string CharacteristicId,
      [property: System.Text.Json.Serialization.JsonPropertyName("descriptorUuid")]
      string DescriptorUuid
    ) : ChromeProtocol.Core.ICommand<AddDescriptorRequestResult>
    {
    }
    /// <param name="DescriptorId">An identifier that uniquely represents this descriptor.</param>
    public record AddDescriptorRequestResult(
      [property: System.Text.Json.Serialization.JsonPropertyName("descriptorId")]
      string DescriptorId
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Removes the descriptor with |descriptorId| from the simulated central.</summary>
    public static Enyim.Iris.Protocol.BluetoothEmulation.RemoveDescriptorRequest RemoveDescriptor(string DescriptorId)    
    {
      return new Enyim.Iris.Protocol.BluetoothEmulation.RemoveDescriptorRequest(DescriptorId);
    }
    /// <summary>Removes the descriptor with |descriptorId| from the simulated central.</summary>
    [ChromeProtocol.Core.MethodName("BluetoothEmulation.removeDescriptor")]
    public record RemoveDescriptorRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("descriptorId")]
      string DescriptorId
    ) : ChromeProtocol.Core.ICommand<RemoveDescriptorRequestResult>
    {
    }
    public record RemoveDescriptorRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Simulates a GATT disconnection from the peripheral with |address|.</summary>
    public static Enyim.Iris.Protocol.BluetoothEmulation.SimulateGATTDisconnectionRequest SimulateGATTDisconnection(string Address)    
    {
      return new Enyim.Iris.Protocol.BluetoothEmulation.SimulateGATTDisconnectionRequest(Address);
    }
    /// <summary>Simulates a GATT disconnection from the peripheral with |address|.</summary>
    [ChromeProtocol.Core.MethodName("BluetoothEmulation.simulateGATTDisconnection")]
    public record SimulateGATTDisconnectionRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("address")]
      string Address
    ) : ChromeProtocol.Core.ICommand<SimulateGATTDisconnectionRequestResult>
    {
    }
    public record SimulateGATTDisconnectionRequestResult() : ChromeProtocol.Core.IType
    {
    }
  }
}
