// <auto-generated />
#nullable enable

namespace Enyim.Iris.Protocol
{
  public static partial class DeviceAccess
  {
    /// <summary>Device request id.</summary>
    [System.Text.Json.Serialization.JsonConverter(typeof(ChromeProtocol.Core.PrimitiveTypeConverter))]
    public record RequestIdType(
      string Value
    ) : ChromeProtocol.Core.PrimitiveType<string>(Value)
    {
    }
    /// <summary>A device id.</summary>
    [System.Text.Json.Serialization.JsonConverter(typeof(ChromeProtocol.Core.PrimitiveTypeConverter))]
    public record DeviceIdType(
      string Value
    ) : ChromeProtocol.Core.PrimitiveType<string>(Value)
    {
    }
    /// <summary>Device information displayed in a user prompt to select a device.</summary>
    /// <param name="Name">Display name as it appears in a device request user prompt.</param>
    public record PromptDeviceType(
      [property: System.Text.Json.Serialization.JsonPropertyName("id")]
      Enyim.Iris.Protocol.DeviceAccess.DeviceIdType Id,
      [property: System.Text.Json.Serialization.JsonPropertyName("name")]
      string Name
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// A device request opened a user prompt to select a device. Respond with the<br/>
    /// selectPrompt or cancelPrompt command.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("DeviceAccess.deviceRequestPrompted")]
    public record DeviceRequestPrompted(
      [property: System.Text.Json.Serialization.JsonPropertyName("id")]
      Enyim.Iris.Protocol.DeviceAccess.RequestIdType Id,
      [property: System.Text.Json.Serialization.JsonPropertyName("devices")]
      System.Collections.Generic.IReadOnlyList<Enyim.Iris.Protocol.DeviceAccess.PromptDeviceType> Devices
    ) : ChromeProtocol.Core.IEvent
    {
    }
    /// <summary>Enable events in this domain.</summary>
    public static Enyim.Iris.Protocol.DeviceAccess.EnableRequest Enable()    
    {
      return new Enyim.Iris.Protocol.DeviceAccess.EnableRequest();
    }
    /// <summary>Enable events in this domain.</summary>
    [ChromeProtocol.Core.MethodName("DeviceAccess.enable")]
    public record EnableRequest() : ChromeProtocol.Core.ICommand<EnableRequestResult>
    {
    }
    public record EnableRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Disable events in this domain.</summary>
    public static Enyim.Iris.Protocol.DeviceAccess.DisableRequest Disable()    
    {
      return new Enyim.Iris.Protocol.DeviceAccess.DisableRequest();
    }
    /// <summary>Disable events in this domain.</summary>
    [ChromeProtocol.Core.MethodName("DeviceAccess.disable")]
    public record DisableRequest() : ChromeProtocol.Core.ICommand<DisableRequestResult>
    {
    }
    public record DisableRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Select a device in response to a DeviceAccess.deviceRequestPrompted event.</summary>
    public static Enyim.Iris.Protocol.DeviceAccess.SelectPromptRequest SelectPrompt(Enyim.Iris.Protocol.DeviceAccess.RequestIdType Id, Enyim.Iris.Protocol.DeviceAccess.DeviceIdType DeviceId)    
    {
      return new Enyim.Iris.Protocol.DeviceAccess.SelectPromptRequest(Id, DeviceId);
    }
    /// <summary>Select a device in response to a DeviceAccess.deviceRequestPrompted event.</summary>
    [ChromeProtocol.Core.MethodName("DeviceAccess.selectPrompt")]
    public record SelectPromptRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("id")]
      Enyim.Iris.Protocol.DeviceAccess.RequestIdType Id,
      [property: System.Text.Json.Serialization.JsonPropertyName("deviceId")]
      Enyim.Iris.Protocol.DeviceAccess.DeviceIdType DeviceId
    ) : ChromeProtocol.Core.ICommand<SelectPromptRequestResult>
    {
    }
    public record SelectPromptRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Cancel a prompt in response to a DeviceAccess.deviceRequestPrompted event.</summary>
    public static Enyim.Iris.Protocol.DeviceAccess.CancelPromptRequest CancelPrompt(Enyim.Iris.Protocol.DeviceAccess.RequestIdType Id)    
    {
      return new Enyim.Iris.Protocol.DeviceAccess.CancelPromptRequest(Id);
    }
    /// <summary>Cancel a prompt in response to a DeviceAccess.deviceRequestPrompted event.</summary>
    [ChromeProtocol.Core.MethodName("DeviceAccess.cancelPrompt")]
    public record CancelPromptRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("id")]
      Enyim.Iris.Protocol.DeviceAccess.RequestIdType Id
    ) : ChromeProtocol.Core.ICommand<CancelPromptRequestResult>
    {
    }
    public record CancelPromptRequestResult() : ChromeProtocol.Core.IType
    {
    }
  }
}
