// <auto-generated />
#nullable enable

namespace Enyim.Iris.Protocol
{
  /// <summary>This domain emulates different environments for the page.</summary>
  public static partial class Emulation
  {
    /// <param name="Top">Overrides safe-area-inset-top.</param>
    /// <param name="TopMax">Overrides safe-area-max-inset-top.</param>
    /// <param name="Left">Overrides safe-area-inset-left.</param>
    /// <param name="LeftMax">Overrides safe-area-max-inset-left.</param>
    /// <param name="Bottom">Overrides safe-area-inset-bottom.</param>
    /// <param name="BottomMax">Overrides safe-area-max-inset-bottom.</param>
    /// <param name="Right">Overrides safe-area-inset-right.</param>
    /// <param name="RightMax">Overrides safe-area-max-inset-right.</param>
    public record SafeAreaInsetsType(
      [property: System.Text.Json.Serialization.JsonPropertyName("top")]
      int? Top = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("topMax")]
      int? TopMax = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("left")]
      int? Left = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("leftMax")]
      int? LeftMax = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("bottom")]
      int? Bottom = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("bottomMax")]
      int? BottomMax = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("right")]
      int? Right = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("rightMax")]
      int? RightMax = default
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Screen orientation.</summary>
    /// <param name="Type">Orientation type.</param>
    /// <param name="Angle">Orientation angle.</param>
    public record ScreenOrientationType(
      [property: System.Text.Json.Serialization.JsonPropertyName("type")]
      string Type,
      [property: System.Text.Json.Serialization.JsonPropertyName("angle")]
      int Angle
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <param name="Orientation">Orientation of a display feature in relation to screen</param>
    /// <param name="Offset">
    /// The offset from the screen origin in either the x (for vertical<br/>
    /// orientation) or y (for horizontal orientation) direction.<br/>
    /// </param>
    /// <param name="MaskLength">
    /// A display feature may mask content such that it is not physically<br/>
    /// displayed - this length along with the offset describes this area.<br/>
    /// A display feature that only splits content will have a 0 mask_length.<br/>
    /// </param>
    public record DisplayFeatureType(
      [property: System.Text.Json.Serialization.JsonPropertyName("orientation")]
      string Orientation,
      [property: System.Text.Json.Serialization.JsonPropertyName("offset")]
      int Offset,
      [property: System.Text.Json.Serialization.JsonPropertyName("maskLength")]
      int MaskLength
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <param name="Type">Current posture of the device</param>
    public record DevicePostureType(
      [property: System.Text.Json.Serialization.JsonPropertyName("type")]
      string Type
    ) : ChromeProtocol.Core.IType
    {
    }
    public record MediaFeatureType(
      [property: System.Text.Json.Serialization.JsonPropertyName("name")]
      string Name,
      [property: System.Text.Json.Serialization.JsonPropertyName("value")]
      string Value
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// advance: If the scheduler runs out of immediate work, the virtual time base may fast forward to<br/>
    /// allow the next delayed task (if any) to run; pause: The virtual time base may not advance;<br/>
    /// pauseIfNetworkFetchesPending: The virtual time base may not advance if there are any pending<br/>
    /// resource fetches.<br/>
    /// </summary>
    [System.Text.Json.Serialization.JsonConverter(typeof(ChromeProtocol.Core.PrimitiveTypeConverter))]
    public record VirtualTimePolicyType(
      string Value
    ) : ChromeProtocol.Core.PrimitiveType<string>(Value)
    {
    }
    /// <summary>Used to specify User Agent Client Hints to emulate. See https://wicg.github.io/ua-client-hints</summary>
    public record UserAgentBrandVersionType(
      [property: System.Text.Json.Serialization.JsonPropertyName("brand")]
      string Brand,
      [property: System.Text.Json.Serialization.JsonPropertyName("version")]
      string Version
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Used to specify User Agent Client Hints to emulate. See https://wicg.github.io/ua-client-hints<br/>
    /// Missing optional values will be filled in by the target with what it would normally use.<br/>
    /// </summary>
    /// <param name="Brands">Brands appearing in Sec-CH-UA.</param>
    /// <param name="FullVersionList">Brands appearing in Sec-CH-UA-Full-Version-List.</param>
    /// <param name="FormFactors">
    /// Used to specify User Agent form-factor values.<br/>
    /// See https://wicg.github.io/ua-client-hints/#sec-ch-ua-form-factors<br/>
    /// </param>
    public record UserAgentMetadataType(
      [property: System.Text.Json.Serialization.JsonPropertyName("platform")]
      string Platform,
      [property: System.Text.Json.Serialization.JsonPropertyName("platformVersion")]
      string PlatformVersion,
      [property: System.Text.Json.Serialization.JsonPropertyName("architecture")]
      string Architecture,
      [property: System.Text.Json.Serialization.JsonPropertyName("model")]
      string Model,
      [property: System.Text.Json.Serialization.JsonPropertyName("mobile")]
      bool Mobile,
      [property: System.Text.Json.Serialization.JsonPropertyName("brands")]
      System.Collections.Generic.IReadOnlyList<Enyim.Iris.Protocol.Emulation.UserAgentBrandVersionType>? Brands = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("fullVersionList")]
      System.Collections.Generic.IReadOnlyList<Enyim.Iris.Protocol.Emulation.UserAgentBrandVersionType>? FullVersionList = default,
      [property: System.Obsolete("This property marked as deprecated in the corresponding CDP definition schema. It may be removed in the future releases.", false)]
      [property: System.Text.Json.Serialization.JsonPropertyName("fullVersion")]
      string? FullVersion = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("bitness")]
      string? Bitness = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("wow64")]
      bool? Wow64 = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("formFactors")]
      System.Collections.Generic.IReadOnlyList<string>? FormFactors = default
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Used to specify sensor types to emulate.<br/>
    /// See https://w3c.github.io/sensors/#automation for more information.<br/>
    /// </summary>
    [System.Text.Json.Serialization.JsonConverter(typeof(ChromeProtocol.Core.PrimitiveTypeConverter))]
    public record SensorTypeType(
      string Value
    ) : ChromeProtocol.Core.PrimitiveType<string>(Value)
    {
    }
    public record SensorMetadataType(
      [property: System.Text.Json.Serialization.JsonPropertyName("available")]
      bool? Available = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("minimumFrequency")]
      double? MinimumFrequency = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("maximumFrequency")]
      double? MaximumFrequency = default
    ) : ChromeProtocol.Core.IType
    {
    }
    public record SensorReadingSingleType(
      [property: System.Text.Json.Serialization.JsonPropertyName("value")]
      double Value
    ) : ChromeProtocol.Core.IType
    {
    }
    public record SensorReadingXYZType(
      [property: System.Text.Json.Serialization.JsonPropertyName("x")]
      double X,
      [property: System.Text.Json.Serialization.JsonPropertyName("y")]
      double Y,
      [property: System.Text.Json.Serialization.JsonPropertyName("z")]
      double Z
    ) : ChromeProtocol.Core.IType
    {
    }
    public record SensorReadingQuaternionType(
      [property: System.Text.Json.Serialization.JsonPropertyName("x")]
      double X,
      [property: System.Text.Json.Serialization.JsonPropertyName("y")]
      double Y,
      [property: System.Text.Json.Serialization.JsonPropertyName("z")]
      double Z,
      [property: System.Text.Json.Serialization.JsonPropertyName("w")]
      double W
    ) : ChromeProtocol.Core.IType
    {
    }
    public record SensorReadingType(
      [property: System.Text.Json.Serialization.JsonPropertyName("single")]
      Enyim.Iris.Protocol.Emulation.SensorReadingSingleType? Single = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("xyz")]
      Enyim.Iris.Protocol.Emulation.SensorReadingXYZType? Xyz = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("quaternion")]
      Enyim.Iris.Protocol.Emulation.SensorReadingQuaternionType? Quaternion = default
    ) : ChromeProtocol.Core.IType
    {
    }
    [System.Text.Json.Serialization.JsonConverter(typeof(ChromeProtocol.Core.PrimitiveTypeConverter))]
    public record PressureSourceType(
      string Value
    ) : ChromeProtocol.Core.PrimitiveType<string>(Value)
    {
    }
    [System.Text.Json.Serialization.JsonConverter(typeof(ChromeProtocol.Core.PrimitiveTypeConverter))]
    public record PressureStateType(
      string Value
    ) : ChromeProtocol.Core.PrimitiveType<string>(Value)
    {
    }
    public record PressureMetadataType(
      [property: System.Text.Json.Serialization.JsonPropertyName("available")]
      bool? Available = default
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <param name="Top">Work area top inset in pixels. Default is 0;</param>
    /// <param name="Left">Work area left inset in pixels. Default is 0;</param>
    /// <param name="Bottom">Work area bottom inset in pixels. Default is 0;</param>
    /// <param name="Right">Work area right inset in pixels. Default is 0;</param>
    public record WorkAreaInsetsType(
      [property: System.Text.Json.Serialization.JsonPropertyName("top")]
      int? Top = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("left")]
      int? Left = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("bottom")]
      int? Bottom = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("right")]
      int? Right = default
    ) : ChromeProtocol.Core.IType
    {
    }
    [System.Text.Json.Serialization.JsonConverter(typeof(ChromeProtocol.Core.PrimitiveTypeConverter))]
    public record ScreenIdType(
      string Value
    ) : ChromeProtocol.Core.PrimitiveType<string>(Value)
    {
    }
    /// <summary>
    /// Screen information similar to the one returned by window.getScreenDetails() method,<br/>
    /// see https://w3c.github.io/window-management/#screendetailed.<br/>
    /// </summary>
    /// <param name="Left">Offset of the left edge of the screen.</param>
    /// <param name="Top">Offset of the top edge of the screen.</param>
    /// <param name="Width">Width of the screen.</param>
    /// <param name="Height">Height of the screen.</param>
    /// <param name="AvailLeft">Offset of the left edge of the available screen area.</param>
    /// <param name="AvailTop">Offset of the top edge of the available screen area.</param>
    /// <param name="AvailWidth">Width of the available screen area.</param>
    /// <param name="AvailHeight">Height of the available screen area.</param>
    /// <param name="DevicePixelRatio">Specifies the screen&#39;s device pixel ratio.</param>
    /// <param name="Orientation">Specifies the screen&#39;s orientation.</param>
    /// <param name="ColorDepth">Specifies the screen&#39;s color depth in bits.</param>
    /// <param name="IsExtended">Indicates whether the device has multiple screens.</param>
    /// <param name="IsInternal">Indicates whether the screen is internal to the device or external, attached to the device.</param>
    /// <param name="IsPrimary">Indicates whether the screen is set as the the operating system primary screen.</param>
    /// <param name="Label">Specifies the descriptive label for the screen.</param>
    /// <param name="Id">Specifies the unique identifier of the screen.</param>
    public record ScreenInfoType(
      [property: System.Text.Json.Serialization.JsonPropertyName("left")]
      int Left,
      [property: System.Text.Json.Serialization.JsonPropertyName("top")]
      int Top,
      [property: System.Text.Json.Serialization.JsonPropertyName("width")]
      int Width,
      [property: System.Text.Json.Serialization.JsonPropertyName("height")]
      int Height,
      [property: System.Text.Json.Serialization.JsonPropertyName("availLeft")]
      int AvailLeft,
      [property: System.Text.Json.Serialization.JsonPropertyName("availTop")]
      int AvailTop,
      [property: System.Text.Json.Serialization.JsonPropertyName("availWidth")]
      int AvailWidth,
      [property: System.Text.Json.Serialization.JsonPropertyName("availHeight")]
      int AvailHeight,
      [property: System.Text.Json.Serialization.JsonPropertyName("devicePixelRatio")]
      double DevicePixelRatio,
      [property: System.Text.Json.Serialization.JsonPropertyName("orientation")]
      Enyim.Iris.Protocol.Emulation.ScreenOrientationType Orientation,
      [property: System.Text.Json.Serialization.JsonPropertyName("colorDepth")]
      int ColorDepth,
      [property: System.Text.Json.Serialization.JsonPropertyName("isExtended")]
      bool IsExtended,
      [property: System.Text.Json.Serialization.JsonPropertyName("isInternal")]
      bool IsInternal,
      [property: System.Text.Json.Serialization.JsonPropertyName("isPrimary")]
      bool IsPrimary,
      [property: System.Text.Json.Serialization.JsonPropertyName("label")]
      string Label,
      [property: System.Text.Json.Serialization.JsonPropertyName("id")]
      Enyim.Iris.Protocol.Emulation.ScreenIdType Id
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Enum of image types that can be disabled.</summary>
    [System.Text.Json.Serialization.JsonConverter(typeof(ChromeProtocol.Core.PrimitiveTypeConverter))]
    public record DisabledImageTypeType(
      string Value
    ) : ChromeProtocol.Core.PrimitiveType<string>(Value)
    {
    }
    /// <summary>Notification sent after the virtual time budget for the current VirtualTimePolicy has run out.</summary>
    [ChromeProtocol.Core.MethodName("Emulation.virtualTimeBudgetExpired")]
    public record VirtualTimeBudgetExpired() : ChromeProtocol.Core.IEvent
    {
    }
    /// <summary>
    /// Fired when a page calls screen.orientation.lock() or screen.orientation.unlock()<br/>
    /// while device emulation is enabled. This allows the DevTools frontend to update the<br/>
    /// emulated device orientation accordingly.<br/>
    /// </summary>
    /// <param name="Locked">Whether the screen orientation is currently locked.</param>
    /// <param name="Orientation">The orientation lock type requested by the page. Only set when locked is true.</param>
    [ChromeProtocol.Core.MethodName("Emulation.screenOrientationLockChanged")]
    public record ScreenOrientationLockChanged(
      [property: System.Text.Json.Serialization.JsonPropertyName("locked")]
      bool Locked,
      [property: System.Text.Json.Serialization.JsonPropertyName("orientation")]
      Enyim.Iris.Protocol.Emulation.ScreenOrientationType? Orientation = default
    ) : ChromeProtocol.Core.IEvent
    {
    }
    /// <summary>Tells whether emulation is supported.</summary>
    [System.Obsolete("This command marked as deprecated in the corresponding CDP definition schema. It may be removed in the future releases.", false)]
    public static Enyim.Iris.Protocol.Emulation.CanEmulateRequest CanEmulate()    
    {
      return new Enyim.Iris.Protocol.Emulation.CanEmulateRequest();
    }
    /// <summary>Tells whether emulation is supported.</summary>
    [ChromeProtocol.Core.MethodName("Emulation.canEmulate")]
    [System.Obsolete("This command marked as deprecated in the corresponding CDP definition schema. It may be removed in the future releases.", false)]
    public record CanEmulateRequest() : ChromeProtocol.Core.ICommand<CanEmulateRequestResult>
    {
    }
    /// <param name="Result">True if emulation is supported.</param>
    [System.Obsolete("This command marked as deprecated in the corresponding CDP definition schema. It may be removed in the future releases.", false)]
    public record CanEmulateRequestResult(
      [property: System.Text.Json.Serialization.JsonPropertyName("result")]
      bool Result
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Clears the overridden device metrics.</summary>
    public static Enyim.Iris.Protocol.Emulation.ClearDeviceMetricsOverrideRequest ClearDeviceMetricsOverride()    
    {
      return new Enyim.Iris.Protocol.Emulation.ClearDeviceMetricsOverrideRequest();
    }
    /// <summary>Clears the overridden device metrics.</summary>
    [ChromeProtocol.Core.MethodName("Emulation.clearDeviceMetricsOverride")]
    public record ClearDeviceMetricsOverrideRequest() : ChromeProtocol.Core.ICommand<ClearDeviceMetricsOverrideRequestResult>
    {
    }
    public record ClearDeviceMetricsOverrideRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Clears the overridden Geolocation Position and Error.</summary>
    public static Enyim.Iris.Protocol.Emulation.ClearGeolocationOverrideRequest ClearGeolocationOverride()    
    {
      return new Enyim.Iris.Protocol.Emulation.ClearGeolocationOverrideRequest();
    }
    /// <summary>Clears the overridden Geolocation Position and Error.</summary>
    [ChromeProtocol.Core.MethodName("Emulation.clearGeolocationOverride")]
    public record ClearGeolocationOverrideRequest() : ChromeProtocol.Core.ICommand<ClearGeolocationOverrideRequestResult>
    {
    }
    public record ClearGeolocationOverrideRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Requests that page scale factor is reset to initial values.</summary>
    public static Enyim.Iris.Protocol.Emulation.ResetPageScaleFactorRequest ResetPageScaleFactor()    
    {
      return new Enyim.Iris.Protocol.Emulation.ResetPageScaleFactorRequest();
    }
    /// <summary>Requests that page scale factor is reset to initial values.</summary>
    [ChromeProtocol.Core.MethodName("Emulation.resetPageScaleFactor")]
    public record ResetPageScaleFactorRequest() : ChromeProtocol.Core.ICommand<ResetPageScaleFactorRequestResult>
    {
    }
    public record ResetPageScaleFactorRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Enables or disables simulating a focused and active page.</summary>
    /// <param name="Enabled">Whether to enable to disable focus emulation.</param>
    public static Enyim.Iris.Protocol.Emulation.SetFocusEmulationEnabledRequest SetFocusEmulationEnabled(bool Enabled)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetFocusEmulationEnabledRequest(Enabled);
    }
    /// <summary>Enables or disables simulating a focused and active page.</summary>
    /// <param name="Enabled">Whether to enable to disable focus emulation.</param>
    [ChromeProtocol.Core.MethodName("Emulation.setFocusEmulationEnabled")]
    public record SetFocusEmulationEnabledRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("enabled")]
      bool Enabled
    ) : ChromeProtocol.Core.ICommand<SetFocusEmulationEnabledRequestResult>
    {
    }
    public record SetFocusEmulationEnabledRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Automatically render all web contents using a dark theme.</summary>
    /// <param name="Enabled">
    /// Whether to enable or disable automatic dark mode.<br/>
    /// If not specified, any existing override will be cleared.<br/>
    /// </param>
    public static Enyim.Iris.Protocol.Emulation.SetAutoDarkModeOverrideRequest SetAutoDarkModeOverride(bool? Enabled = default)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetAutoDarkModeOverrideRequest(Enabled);
    }
    /// <summary>Automatically render all web contents using a dark theme.</summary>
    /// <param name="Enabled">
    /// Whether to enable or disable automatic dark mode.<br/>
    /// If not specified, any existing override will be cleared.<br/>
    /// </param>
    [ChromeProtocol.Core.MethodName("Emulation.setAutoDarkModeOverride")]
    public record SetAutoDarkModeOverrideRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("enabled")]
      bool? Enabled = default
    ) : ChromeProtocol.Core.ICommand<SetAutoDarkModeOverrideRequestResult>
    {
    }
    public record SetAutoDarkModeOverrideRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Enables CPU throttling to emulate slow CPUs.</summary>
    /// <param name="Rate">Throttling rate as a slowdown factor (1 is no throttle, 2 is 2x slowdown, etc).</param>
    public static Enyim.Iris.Protocol.Emulation.SetCPUThrottlingRateRequest SetCPUThrottlingRate(double Rate)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetCPUThrottlingRateRequest(Rate);
    }
    /// <summary>Enables CPU throttling to emulate slow CPUs.</summary>
    /// <param name="Rate">Throttling rate as a slowdown factor (1 is no throttle, 2 is 2x slowdown, etc).</param>
    [ChromeProtocol.Core.MethodName("Emulation.setCPUThrottlingRate")]
    public record SetCPUThrottlingRateRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("rate")]
      double Rate
    ) : ChromeProtocol.Core.ICommand<SetCPUThrottlingRateRequestResult>
    {
    }
    public record SetCPUThrottlingRateRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Sets or clears an override of the default background color of the frame. This override is used<br/>
    /// if the content does not specify one.<br/>
    /// </summary>
    /// <param name="Color">
    /// RGBA of the default background color. If not specified, any existing override will be<br/>
    /// cleared.<br/>
    /// </param>
    public static Enyim.Iris.Protocol.Emulation.SetDefaultBackgroundColorOverrideRequest SetDefaultBackgroundColorOverride(Enyim.Iris.Protocol.DOM.RGBAType? Color = default)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetDefaultBackgroundColorOverrideRequest(Color);
    }
    /// <summary>
    /// Sets or clears an override of the default background color of the frame. This override is used<br/>
    /// if the content does not specify one.<br/>
    /// </summary>
    /// <param name="Color">
    /// RGBA of the default background color. If not specified, any existing override will be<br/>
    /// cleared.<br/>
    /// </param>
    [ChromeProtocol.Core.MethodName("Emulation.setDefaultBackgroundColorOverride")]
    public record SetDefaultBackgroundColorOverrideRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("color")]
      Enyim.Iris.Protocol.DOM.RGBAType? Color = default
    ) : ChromeProtocol.Core.ICommand<SetDefaultBackgroundColorOverrideRequestResult>
    {
    }
    public record SetDefaultBackgroundColorOverrideRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Overrides the values for env(safe-area-inset-*) and env(safe-area-max-inset-*). Unset values will cause the<br/>
    /// respective variables to be undefined, even if previously overridden.<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.Emulation.SetSafeAreaInsetsOverrideRequest SetSafeAreaInsetsOverride(Enyim.Iris.Protocol.Emulation.SafeAreaInsetsType Insets)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetSafeAreaInsetsOverrideRequest(Insets);
    }
    /// <summary>
    /// Overrides the values for env(safe-area-inset-*) and env(safe-area-max-inset-*). Unset values will cause the<br/>
    /// respective variables to be undefined, even if previously overridden.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("Emulation.setSafeAreaInsetsOverride")]
    public record SetSafeAreaInsetsOverrideRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("insets")]
      Enyim.Iris.Protocol.Emulation.SafeAreaInsetsType Insets
    ) : ChromeProtocol.Core.ICommand<SetSafeAreaInsetsOverrideRequestResult>
    {
    }
    public record SetSafeAreaInsetsOverrideRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Overrides the values of device screen dimensions (window.screen.width, window.screen.height,<br/>
    /// window.innerWidth, window.innerHeight, and &quot;device-width&quot;/&quot;device-height&quot;-related CSS media<br/>
    /// query results).<br/>
    /// </summary>
    /// <param name="Width">Overriding width value in pixels (minimum 0, maximum 10000000). 0 disables the override.</param>
    /// <param name="Height">Overriding height value in pixels (minimum 0, maximum 10000000). 0 disables the override.</param>
    /// <param name="DeviceScaleFactor">Overriding device scale factor value. 0 disables the override.</param>
    /// <param name="Mobile">
    /// Whether to emulate mobile device. This includes viewport meta tag, overlay scrollbars, text<br/>
    /// autosizing and more.<br/>
    /// </param>
    /// <param name="Scale">Scale to apply to resulting view image.</param>
    /// <param name="ScreenWidth">Overriding screen width value in pixels (minimum 0, maximum 10000000).</param>
    /// <param name="ScreenHeight">Overriding screen height value in pixels (minimum 0, maximum 10000000).</param>
    /// <param name="PositionX">Overriding view X position on screen in pixels (minimum 0, maximum 10000000).</param>
    /// <param name="PositionY">Overriding view Y position on screen in pixels (minimum 0, maximum 10000000).</param>
    /// <param name="DontSetVisibleSize">Do not set visible view size, rely upon explicit setVisibleSize call.</param>
    /// <param name="ScreenOrientation">Screen orientation override.</param>
    /// <param name="Viewport">
    /// If set, the visible area of the page will be overridden to this viewport. This viewport<br/>
    /// change is not observed by the page, e.g. viewport-relative elements do not change positions.<br/>
    /// </param>
    /// <param name="DisplayFeature">
    /// If set, the display feature of a multi-segment screen. If not set, multi-segment support<br/>
    /// is turned-off.<br/>
    /// Deprecated, use Emulation.setDisplayFeaturesOverride.<br/>
    /// </param>
    /// <param name="DevicePosture">
    /// If set, the posture of a foldable device. If not set the posture is set<br/>
    /// to continuous.<br/>
    /// Deprecated, use Emulation.setDevicePostureOverride.<br/>
    /// </param>
    /// <param name="ScrollbarType">Scrollbar type. Default: `default`.</param>
    /// <param name="ScreenOrientationLockEmulation">
    /// If set to true, enables screen orientation lock emulation, which<br/>
    /// intercepts screen.orientation.lock() calls from the page and reports<br/>
    /// orientation changes via screenOrientationLockChanged events. This is<br/>
    /// useful for emulating mobile device orientation lock behavior in<br/>
    /// responsive design mode.<br/>
    /// </param>
    public static Enyim.Iris.Protocol.Emulation.SetDeviceMetricsOverrideRequest SetDeviceMetricsOverride(int Width, int Height, double DeviceScaleFactor, bool Mobile, double? Scale = default, int? ScreenWidth = default, int? ScreenHeight = default, int? PositionX = default, int? PositionY = default, bool? DontSetVisibleSize = default, Enyim.Iris.Protocol.Emulation.ScreenOrientationType? ScreenOrientation = default, Enyim.Iris.Protocol.Page.ViewportType? Viewport = default, Enyim.Iris.Protocol.Emulation.DisplayFeatureType? DisplayFeature = default, Enyim.Iris.Protocol.Emulation.DevicePostureType? DevicePosture = default, string? ScrollbarType = default, bool? ScreenOrientationLockEmulation = default)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetDeviceMetricsOverrideRequest(Width, Height, DeviceScaleFactor, Mobile, Scale, ScreenWidth, ScreenHeight, PositionX, PositionY, DontSetVisibleSize, ScreenOrientation, Viewport, DisplayFeature, DevicePosture, ScrollbarType, ScreenOrientationLockEmulation);
    }
    /// <summary>
    /// Overrides the values of device screen dimensions (window.screen.width, window.screen.height,<br/>
    /// window.innerWidth, window.innerHeight, and &quot;device-width&quot;/&quot;device-height&quot;-related CSS media<br/>
    /// query results).<br/>
    /// </summary>
    /// <param name="Width">Overriding width value in pixels (minimum 0, maximum 10000000). 0 disables the override.</param>
    /// <param name="Height">Overriding height value in pixels (minimum 0, maximum 10000000). 0 disables the override.</param>
    /// <param name="DeviceScaleFactor">Overriding device scale factor value. 0 disables the override.</param>
    /// <param name="Mobile">
    /// Whether to emulate mobile device. This includes viewport meta tag, overlay scrollbars, text<br/>
    /// autosizing and more.<br/>
    /// </param>
    /// <param name="Scale">Scale to apply to resulting view image.</param>
    /// <param name="ScreenWidth">Overriding screen width value in pixels (minimum 0, maximum 10000000).</param>
    /// <param name="ScreenHeight">Overriding screen height value in pixels (minimum 0, maximum 10000000).</param>
    /// <param name="PositionX">Overriding view X position on screen in pixels (minimum 0, maximum 10000000).</param>
    /// <param name="PositionY">Overriding view Y position on screen in pixels (minimum 0, maximum 10000000).</param>
    /// <param name="DontSetVisibleSize">Do not set visible view size, rely upon explicit setVisibleSize call.</param>
    /// <param name="ScreenOrientation">Screen orientation override.</param>
    /// <param name="Viewport">
    /// If set, the visible area of the page will be overridden to this viewport. This viewport<br/>
    /// change is not observed by the page, e.g. viewport-relative elements do not change positions.<br/>
    /// </param>
    /// <param name="DisplayFeature">
    /// If set, the display feature of a multi-segment screen. If not set, multi-segment support<br/>
    /// is turned-off.<br/>
    /// Deprecated, use Emulation.setDisplayFeaturesOverride.<br/>
    /// </param>
    /// <param name="DevicePosture">
    /// If set, the posture of a foldable device. If not set the posture is set<br/>
    /// to continuous.<br/>
    /// Deprecated, use Emulation.setDevicePostureOverride.<br/>
    /// </param>
    /// <param name="ScrollbarType">Scrollbar type. Default: `default`.</param>
    /// <param name="ScreenOrientationLockEmulation">
    /// If set to true, enables screen orientation lock emulation, which<br/>
    /// intercepts screen.orientation.lock() calls from the page and reports<br/>
    /// orientation changes via screenOrientationLockChanged events. This is<br/>
    /// useful for emulating mobile device orientation lock behavior in<br/>
    /// responsive design mode.<br/>
    /// </param>
    [ChromeProtocol.Core.MethodName("Emulation.setDeviceMetricsOverride")]
    public record SetDeviceMetricsOverrideRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("width")]
      int Width,
      [property: System.Text.Json.Serialization.JsonPropertyName("height")]
      int Height,
      [property: System.Text.Json.Serialization.JsonPropertyName("deviceScaleFactor")]
      double DeviceScaleFactor,
      [property: System.Text.Json.Serialization.JsonPropertyName("mobile")]
      bool Mobile,
      [property: System.Text.Json.Serialization.JsonPropertyName("scale")]
      double? Scale = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("screenWidth")]
      int? ScreenWidth = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("screenHeight")]
      int? ScreenHeight = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("positionX")]
      int? PositionX = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("positionY")]
      int? PositionY = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("dontSetVisibleSize")]
      bool? DontSetVisibleSize = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("screenOrientation")]
      Enyim.Iris.Protocol.Emulation.ScreenOrientationType? ScreenOrientation = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("viewport")]
      Enyim.Iris.Protocol.Page.ViewportType? Viewport = default,
      [property: System.Obsolete("This property marked as deprecated in the corresponding CDP definition schema. It may be removed in the future releases.", false)]
      [property: System.Text.Json.Serialization.JsonPropertyName("displayFeature")]
      Enyim.Iris.Protocol.Emulation.DisplayFeatureType? DisplayFeature = default,
      [property: System.Obsolete("This property marked as deprecated in the corresponding CDP definition schema. It may be removed in the future releases.", false)]
      [property: System.Text.Json.Serialization.JsonPropertyName("devicePosture")]
      Enyim.Iris.Protocol.Emulation.DevicePostureType? DevicePosture = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("scrollbarType")]
      string? ScrollbarType = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("screenOrientationLockEmulation")]
      bool? ScreenOrientationLockEmulation = default
    ) : ChromeProtocol.Core.ICommand<SetDeviceMetricsOverrideRequestResult>
    {
    }
    public record SetDeviceMetricsOverrideRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Start reporting the given posture value to the Device Posture API.<br/>
    /// This override can also be set in setDeviceMetricsOverride().<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.Emulation.SetDevicePostureOverrideRequest SetDevicePostureOverride(Enyim.Iris.Protocol.Emulation.DevicePostureType Posture)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetDevicePostureOverrideRequest(Posture);
    }
    /// <summary>
    /// Start reporting the given posture value to the Device Posture API.<br/>
    /// This override can also be set in setDeviceMetricsOverride().<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("Emulation.setDevicePostureOverride")]
    public record SetDevicePostureOverrideRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("posture")]
      Enyim.Iris.Protocol.Emulation.DevicePostureType Posture
    ) : ChromeProtocol.Core.ICommand<SetDevicePostureOverrideRequestResult>
    {
    }
    public record SetDevicePostureOverrideRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Clears a device posture override set with either setDeviceMetricsOverride()<br/>
    /// or setDevicePostureOverride() and starts using posture information from the<br/>
    /// platform again.<br/>
    /// Does nothing if no override is set.<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.Emulation.ClearDevicePostureOverrideRequest ClearDevicePostureOverride()    
    {
      return new Enyim.Iris.Protocol.Emulation.ClearDevicePostureOverrideRequest();
    }
    /// <summary>
    /// Clears a device posture override set with either setDeviceMetricsOverride()<br/>
    /// or setDevicePostureOverride() and starts using posture information from the<br/>
    /// platform again.<br/>
    /// Does nothing if no override is set.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("Emulation.clearDevicePostureOverride")]
    public record ClearDevicePostureOverrideRequest() : ChromeProtocol.Core.ICommand<ClearDevicePostureOverrideRequestResult>
    {
    }
    public record ClearDevicePostureOverrideRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Start using the given display features to pupulate the Viewport Segments API.<br/>
    /// This override can also be set in setDeviceMetricsOverride().<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.Emulation.SetDisplayFeaturesOverrideRequest SetDisplayFeaturesOverride(System.Collections.Generic.IReadOnlyList<Enyim.Iris.Protocol.Emulation.DisplayFeatureType> Features)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetDisplayFeaturesOverrideRequest(Features);
    }
    /// <summary>
    /// Start using the given display features to pupulate the Viewport Segments API.<br/>
    /// This override can also be set in setDeviceMetricsOverride().<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("Emulation.setDisplayFeaturesOverride")]
    public record SetDisplayFeaturesOverrideRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("features")]
      System.Collections.Generic.IReadOnlyList<Enyim.Iris.Protocol.Emulation.DisplayFeatureType> Features
    ) : ChromeProtocol.Core.ICommand<SetDisplayFeaturesOverrideRequestResult>
    {
    }
    public record SetDisplayFeaturesOverrideRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Clears the display features override set with either setDeviceMetricsOverride()<br/>
    /// or setDisplayFeaturesOverride() and starts using display features from the<br/>
    /// platform again.<br/>
    /// Does nothing if no override is set.<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.Emulation.ClearDisplayFeaturesOverrideRequest ClearDisplayFeaturesOverride()    
    {
      return new Enyim.Iris.Protocol.Emulation.ClearDisplayFeaturesOverrideRequest();
    }
    /// <summary>
    /// Clears the display features override set with either setDeviceMetricsOverride()<br/>
    /// or setDisplayFeaturesOverride() and starts using display features from the<br/>
    /// platform again.<br/>
    /// Does nothing if no override is set.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("Emulation.clearDisplayFeaturesOverride")]
    public record ClearDisplayFeaturesOverrideRequest() : ChromeProtocol.Core.ICommand<ClearDisplayFeaturesOverrideRequestResult>
    {
    }
    public record ClearDisplayFeaturesOverrideRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <param name="Hidden">Whether scrollbars should be always hidden.</param>
    public static Enyim.Iris.Protocol.Emulation.SetScrollbarsHiddenRequest SetScrollbarsHidden(bool Hidden)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetScrollbarsHiddenRequest(Hidden);
    }
    /// <param name="Hidden">Whether scrollbars should be always hidden.</param>
    [ChromeProtocol.Core.MethodName("Emulation.setScrollbarsHidden")]
    public record SetScrollbarsHiddenRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("hidden")]
      bool Hidden
    ) : ChromeProtocol.Core.ICommand<SetScrollbarsHiddenRequestResult>
    {
    }
    public record SetScrollbarsHiddenRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <param name="Disabled">Whether document.coookie API should be disabled.</param>
    public static Enyim.Iris.Protocol.Emulation.SetDocumentCookieDisabledRequest SetDocumentCookieDisabled(bool Disabled)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetDocumentCookieDisabledRequest(Disabled);
    }
    /// <param name="Disabled">Whether document.coookie API should be disabled.</param>
    [ChromeProtocol.Core.MethodName("Emulation.setDocumentCookieDisabled")]
    public record SetDocumentCookieDisabledRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("disabled")]
      bool Disabled
    ) : ChromeProtocol.Core.ICommand<SetDocumentCookieDisabledRequestResult>
    {
    }
    public record SetDocumentCookieDisabledRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <param name="Enabled">Whether touch emulation based on mouse input should be enabled.</param>
    /// <param name="Configuration">Touch/gesture events configuration. Default: current platform.</param>
    public static Enyim.Iris.Protocol.Emulation.SetEmitTouchEventsForMouseRequest SetEmitTouchEventsForMouse(bool Enabled, string? Configuration = default)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetEmitTouchEventsForMouseRequest(Enabled, Configuration);
    }
    /// <param name="Enabled">Whether touch emulation based on mouse input should be enabled.</param>
    /// <param name="Configuration">Touch/gesture events configuration. Default: current platform.</param>
    [ChromeProtocol.Core.MethodName("Emulation.setEmitTouchEventsForMouse")]
    public record SetEmitTouchEventsForMouseRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("enabled")]
      bool Enabled,
      [property: System.Text.Json.Serialization.JsonPropertyName("configuration")]
      string? Configuration = default
    ) : ChromeProtocol.Core.ICommand<SetEmitTouchEventsForMouseRequestResult>
    {
    }
    public record SetEmitTouchEventsForMouseRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Emulates the given media type or media feature for CSS media queries.</summary>
    /// <param name="Media">Media type to emulate. Empty string disables the override.</param>
    /// <param name="Features">Media features to emulate.</param>
    public static Enyim.Iris.Protocol.Emulation.SetEmulatedMediaRequest SetEmulatedMedia(string? Media = default, System.Collections.Generic.IReadOnlyList<Enyim.Iris.Protocol.Emulation.MediaFeatureType>? Features = default)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetEmulatedMediaRequest(Media, Features);
    }
    /// <summary>Emulates the given media type or media feature for CSS media queries.</summary>
    /// <param name="Media">Media type to emulate. Empty string disables the override.</param>
    /// <param name="Features">Media features to emulate.</param>
    [ChromeProtocol.Core.MethodName("Emulation.setEmulatedMedia")]
    public record SetEmulatedMediaRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("media")]
      string? Media = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("features")]
      System.Collections.Generic.IReadOnlyList<Enyim.Iris.Protocol.Emulation.MediaFeatureType>? Features = default
    ) : ChromeProtocol.Core.ICommand<SetEmulatedMediaRequestResult>
    {
    }
    public record SetEmulatedMediaRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Emulates the given vision deficiency.</summary>
    /// <param name="Type">
    /// Vision deficiency to emulate. Order: best-effort emulations come first, followed by any<br/>
    /// physiologically accurate emulations for medically recognized color vision deficiencies.<br/>
    /// </param>
    public static Enyim.Iris.Protocol.Emulation.SetEmulatedVisionDeficiencyRequest SetEmulatedVisionDeficiency(string Type)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetEmulatedVisionDeficiencyRequest(Type);
    }
    /// <summary>Emulates the given vision deficiency.</summary>
    /// <param name="Type">
    /// Vision deficiency to emulate. Order: best-effort emulations come first, followed by any<br/>
    /// physiologically accurate emulations for medically recognized color vision deficiencies.<br/>
    /// </param>
    [ChromeProtocol.Core.MethodName("Emulation.setEmulatedVisionDeficiency")]
    public record SetEmulatedVisionDeficiencyRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("type")]
      string Type
    ) : ChromeProtocol.Core.ICommand<SetEmulatedVisionDeficiencyRequestResult>
    {
    }
    public record SetEmulatedVisionDeficiencyRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Emulates the given OS text scale.</summary>
    public static Enyim.Iris.Protocol.Emulation.SetEmulatedOSTextScaleRequest SetEmulatedOSTextScale(double? Scale = default)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetEmulatedOSTextScaleRequest(Scale);
    }
    /// <summary>Emulates the given OS text scale.</summary>
    [ChromeProtocol.Core.MethodName("Emulation.setEmulatedOSTextScale")]
    public record SetEmulatedOSTextScaleRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("scale")]
      double? Scale = default
    ) : ChromeProtocol.Core.ICommand<SetEmulatedOSTextScaleRequestResult>
    {
    }
    public record SetEmulatedOSTextScaleRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Overrides the Geolocation Position or Error. Omitting latitude, longitude or<br/>
    /// accuracy emulates position unavailable.<br/>
    /// </summary>
    /// <param name="Latitude">Mock latitude</param>
    /// <param name="Longitude">Mock longitude</param>
    /// <param name="Accuracy">Mock accuracy</param>
    /// <param name="Altitude">Mock altitude</param>
    /// <param name="AltitudeAccuracy">Mock altitudeAccuracy</param>
    /// <param name="Heading">Mock heading</param>
    /// <param name="Speed">Mock speed</param>
    public static Enyim.Iris.Protocol.Emulation.SetGeolocationOverrideRequest SetGeolocationOverride(double? Latitude = default, double? Longitude = default, double? Accuracy = default, double? Altitude = default, double? AltitudeAccuracy = default, double? Heading = default, double? Speed = default)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetGeolocationOverrideRequest(Latitude, Longitude, Accuracy, Altitude, AltitudeAccuracy, Heading, Speed);
    }
    /// <summary>
    /// Overrides the Geolocation Position or Error. Omitting latitude, longitude or<br/>
    /// accuracy emulates position unavailable.<br/>
    /// </summary>
    /// <param name="Latitude">Mock latitude</param>
    /// <param name="Longitude">Mock longitude</param>
    /// <param name="Accuracy">Mock accuracy</param>
    /// <param name="Altitude">Mock altitude</param>
    /// <param name="AltitudeAccuracy">Mock altitudeAccuracy</param>
    /// <param name="Heading">Mock heading</param>
    /// <param name="Speed">Mock speed</param>
    [ChromeProtocol.Core.MethodName("Emulation.setGeolocationOverride")]
    public record SetGeolocationOverrideRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("latitude")]
      double? Latitude = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("longitude")]
      double? Longitude = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("accuracy")]
      double? Accuracy = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("altitude")]
      double? Altitude = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("altitudeAccuracy")]
      double? AltitudeAccuracy = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("heading")]
      double? Heading = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("speed")]
      double? Speed = default
    ) : ChromeProtocol.Core.ICommand<SetGeolocationOverrideRequestResult>
    {
    }
    public record SetGeolocationOverrideRequestResult() : ChromeProtocol.Core.IType
    {
    }
    public static Enyim.Iris.Protocol.Emulation.GetOverriddenSensorInformationRequest GetOverriddenSensorInformation(Enyim.Iris.Protocol.Emulation.SensorTypeType Type)    
    {
      return new Enyim.Iris.Protocol.Emulation.GetOverriddenSensorInformationRequest(Type);
    }
    [ChromeProtocol.Core.MethodName("Emulation.getOverriddenSensorInformation")]
    public record GetOverriddenSensorInformationRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("type")]
      Enyim.Iris.Protocol.Emulation.SensorTypeType Type
    ) : ChromeProtocol.Core.ICommand<GetOverriddenSensorInformationRequestResult>
    {
    }
    public record GetOverriddenSensorInformationRequestResult(
      [property: System.Text.Json.Serialization.JsonPropertyName("requestedSamplingFrequency")]
      double RequestedSamplingFrequency
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Overrides a platform sensor of a given type. If |enabled| is true, calls to<br/>
    /// Sensor.start() will use a virtual sensor as backend rather than fetching<br/>
    /// data from a real hardware sensor. Otherwise, existing virtual<br/>
    /// sensor-backend Sensor objects will fire an error event and new calls to<br/>
    /// Sensor.start() will attempt to use a real sensor instead.<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.Emulation.SetSensorOverrideEnabledRequest SetSensorOverrideEnabled(bool Enabled, Enyim.Iris.Protocol.Emulation.SensorTypeType Type, Enyim.Iris.Protocol.Emulation.SensorMetadataType? Metadata = default)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetSensorOverrideEnabledRequest(Enabled, Type, Metadata);
    }
    /// <summary>
    /// Overrides a platform sensor of a given type. If |enabled| is true, calls to<br/>
    /// Sensor.start() will use a virtual sensor as backend rather than fetching<br/>
    /// data from a real hardware sensor. Otherwise, existing virtual<br/>
    /// sensor-backend Sensor objects will fire an error event and new calls to<br/>
    /// Sensor.start() will attempt to use a real sensor instead.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("Emulation.setSensorOverrideEnabled")]
    public record SetSensorOverrideEnabledRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("enabled")]
      bool Enabled,
      [property: System.Text.Json.Serialization.JsonPropertyName("type")]
      Enyim.Iris.Protocol.Emulation.SensorTypeType Type,
      [property: System.Text.Json.Serialization.JsonPropertyName("metadata")]
      Enyim.Iris.Protocol.Emulation.SensorMetadataType? Metadata = default
    ) : ChromeProtocol.Core.ICommand<SetSensorOverrideEnabledRequestResult>
    {
    }
    public record SetSensorOverrideEnabledRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Updates the sensor readings reported by a sensor type previously overridden<br/>
    /// by setSensorOverrideEnabled.<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.Emulation.SetSensorOverrideReadingsRequest SetSensorOverrideReadings(Enyim.Iris.Protocol.Emulation.SensorTypeType Type, Enyim.Iris.Protocol.Emulation.SensorReadingType Reading)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetSensorOverrideReadingsRequest(Type, Reading);
    }
    /// <summary>
    /// Updates the sensor readings reported by a sensor type previously overridden<br/>
    /// by setSensorOverrideEnabled.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("Emulation.setSensorOverrideReadings")]
    public record SetSensorOverrideReadingsRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("type")]
      Enyim.Iris.Protocol.Emulation.SensorTypeType Type,
      [property: System.Text.Json.Serialization.JsonPropertyName("reading")]
      Enyim.Iris.Protocol.Emulation.SensorReadingType Reading
    ) : ChromeProtocol.Core.ICommand<SetSensorOverrideReadingsRequestResult>
    {
    }
    public record SetSensorOverrideReadingsRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Overrides a pressure source of a given type, as used by the Compute<br/>
    /// Pressure API, so that updates to PressureObserver.observe() are provided<br/>
    /// via setPressureStateOverride instead of being retrieved from<br/>
    /// platform-provided telemetry data.<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.Emulation.SetPressureSourceOverrideEnabledRequest SetPressureSourceOverrideEnabled(bool Enabled, Enyim.Iris.Protocol.Emulation.PressureSourceType Source, Enyim.Iris.Protocol.Emulation.PressureMetadataType? Metadata = default)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetPressureSourceOverrideEnabledRequest(Enabled, Source, Metadata);
    }
    /// <summary>
    /// Overrides a pressure source of a given type, as used by the Compute<br/>
    /// Pressure API, so that updates to PressureObserver.observe() are provided<br/>
    /// via setPressureStateOverride instead of being retrieved from<br/>
    /// platform-provided telemetry data.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("Emulation.setPressureSourceOverrideEnabled")]
    public record SetPressureSourceOverrideEnabledRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("enabled")]
      bool Enabled,
      [property: System.Text.Json.Serialization.JsonPropertyName("source")]
      Enyim.Iris.Protocol.Emulation.PressureSourceType Source,
      [property: System.Text.Json.Serialization.JsonPropertyName("metadata")]
      Enyim.Iris.Protocol.Emulation.PressureMetadataType? Metadata = default
    ) : ChromeProtocol.Core.ICommand<SetPressureSourceOverrideEnabledRequestResult>
    {
    }
    public record SetPressureSourceOverrideEnabledRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Provides a given pressure state that will be processed and eventually be<br/>
    /// delivered to PressureObserver users. |source| must have been previously<br/>
    /// overridden by setPressureSourceOverrideEnabled.<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.Emulation.SetPressureStateOverrideRequest SetPressureStateOverride(Enyim.Iris.Protocol.Emulation.PressureSourceType Source, Enyim.Iris.Protocol.Emulation.PressureStateType State)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetPressureStateOverrideRequest(Source, State);
    }
    /// <summary>
    /// Provides a given pressure state that will be processed and eventually be<br/>
    /// delivered to PressureObserver users. |source| must have been previously<br/>
    /// overridden by setPressureSourceOverrideEnabled.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("Emulation.setPressureStateOverride")]
    public record SetPressureStateOverrideRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("source")]
      Enyim.Iris.Protocol.Emulation.PressureSourceType Source,
      [property: System.Text.Json.Serialization.JsonPropertyName("state")]
      Enyim.Iris.Protocol.Emulation.PressureStateType State
    ) : ChromeProtocol.Core.ICommand<SetPressureStateOverrideRequestResult>
    {
    }
    public record SetPressureStateOverrideRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Overrides the Idle state.</summary>
    /// <param name="IsUserActive">Mock isUserActive</param>
    /// <param name="IsScreenUnlocked">Mock isScreenUnlocked</param>
    public static Enyim.Iris.Protocol.Emulation.SetIdleOverrideRequest SetIdleOverride(bool IsUserActive, bool IsScreenUnlocked)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetIdleOverrideRequest(IsUserActive, IsScreenUnlocked);
    }
    /// <summary>Overrides the Idle state.</summary>
    /// <param name="IsUserActive">Mock isUserActive</param>
    /// <param name="IsScreenUnlocked">Mock isScreenUnlocked</param>
    [ChromeProtocol.Core.MethodName("Emulation.setIdleOverride")]
    public record SetIdleOverrideRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("isUserActive")]
      bool IsUserActive,
      [property: System.Text.Json.Serialization.JsonPropertyName("isScreenUnlocked")]
      bool IsScreenUnlocked
    ) : ChromeProtocol.Core.ICommand<SetIdleOverrideRequestResult>
    {
    }
    public record SetIdleOverrideRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Clears Idle state overrides.</summary>
    public static Enyim.Iris.Protocol.Emulation.ClearIdleOverrideRequest ClearIdleOverride()    
    {
      return new Enyim.Iris.Protocol.Emulation.ClearIdleOverrideRequest();
    }
    /// <summary>Clears Idle state overrides.</summary>
    [ChromeProtocol.Core.MethodName("Emulation.clearIdleOverride")]
    public record ClearIdleOverrideRequest() : ChromeProtocol.Core.ICommand<ClearIdleOverrideRequestResult>
    {
    }
    public record ClearIdleOverrideRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Overrides value returned by the javascript navigator object.</summary>
    /// <param name="Platform">The platform navigator.platform should return.</param>
    [System.Obsolete("This command marked as deprecated in the corresponding CDP definition schema. It may be removed in the future releases.", false)]
    public static Enyim.Iris.Protocol.Emulation.SetNavigatorOverridesRequest SetNavigatorOverrides(string Platform)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetNavigatorOverridesRequest(Platform);
    }
    /// <summary>Overrides value returned by the javascript navigator object.</summary>
    /// <param name="Platform">The platform navigator.platform should return.</param>
    [ChromeProtocol.Core.MethodName("Emulation.setNavigatorOverrides")]
    [System.Obsolete("This command marked as deprecated in the corresponding CDP definition schema. It may be removed in the future releases.", false)]
    public record SetNavigatorOverridesRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("platform")]
      string Platform
    ) : ChromeProtocol.Core.ICommand<SetNavigatorOverridesRequestResult>
    {
    }
    [System.Obsolete("This command marked as deprecated in the corresponding CDP definition schema. It may be removed in the future releases.", false)]
    public record SetNavigatorOverridesRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Sets a specified page scale factor.</summary>
    /// <param name="PageScaleFactor">Page scale factor.</param>
    public static Enyim.Iris.Protocol.Emulation.SetPageScaleFactorRequest SetPageScaleFactor(double PageScaleFactor)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetPageScaleFactorRequest(PageScaleFactor);
    }
    /// <summary>Sets a specified page scale factor.</summary>
    /// <param name="PageScaleFactor">Page scale factor.</param>
    [ChromeProtocol.Core.MethodName("Emulation.setPageScaleFactor")]
    public record SetPageScaleFactorRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("pageScaleFactor")]
      double PageScaleFactor
    ) : ChromeProtocol.Core.ICommand<SetPageScaleFactorRequestResult>
    {
    }
    public record SetPageScaleFactorRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Switches script execution in the page.</summary>
    /// <param name="Value">Whether script execution should be disabled in the page.</param>
    public static Enyim.Iris.Protocol.Emulation.SetScriptExecutionDisabledRequest SetScriptExecutionDisabled(bool Value)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetScriptExecutionDisabledRequest(Value);
    }
    /// <summary>Switches script execution in the page.</summary>
    /// <param name="Value">Whether script execution should be disabled in the page.</param>
    [ChromeProtocol.Core.MethodName("Emulation.setScriptExecutionDisabled")]
    public record SetScriptExecutionDisabledRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("value")]
      bool Value
    ) : ChromeProtocol.Core.ICommand<SetScriptExecutionDisabledRequestResult>
    {
    }
    public record SetScriptExecutionDisabledRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Enables touch on platforms which do not support them.</summary>
    /// <param name="Enabled">Whether the touch event emulation should be enabled.</param>
    /// <param name="MaxTouchPoints">Maximum touch points supported. Defaults to one.</param>
    public static Enyim.Iris.Protocol.Emulation.SetTouchEmulationEnabledRequest SetTouchEmulationEnabled(bool Enabled, int? MaxTouchPoints = default)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetTouchEmulationEnabledRequest(Enabled, MaxTouchPoints);
    }
    /// <summary>Enables touch on platforms which do not support them.</summary>
    /// <param name="Enabled">Whether the touch event emulation should be enabled.</param>
    /// <param name="MaxTouchPoints">Maximum touch points supported. Defaults to one.</param>
    [ChromeProtocol.Core.MethodName("Emulation.setTouchEmulationEnabled")]
    public record SetTouchEmulationEnabledRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("enabled")]
      bool Enabled,
      [property: System.Text.Json.Serialization.JsonPropertyName("maxTouchPoints")]
      int? MaxTouchPoints = default
    ) : ChromeProtocol.Core.ICommand<SetTouchEmulationEnabledRequestResult>
    {
    }
    public record SetTouchEmulationEnabledRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Turns on virtual time for all frames (replacing real-time with a synthetic time source) and sets<br/>
    /// the current virtual time policy.  Note this supersedes any previous time budget.<br/>
    /// </summary>
    /// <param name="Budget">
    /// If set, after this many virtual milliseconds have elapsed virtual time will be paused and a<br/>
    /// virtualTimeBudgetExpired event is sent.<br/>
    /// </param>
    /// <param name="MaxVirtualTimeTaskStarvationCount">
    /// If set this specifies the maximum number of tasks that can be run before virtual is forced<br/>
    /// forwards to prevent deadlock.<br/>
    /// </param>
    /// <param name="InitialVirtualTime">If set, base::Time::Now will be overridden to initially return this value.</param>
    public static Enyim.Iris.Protocol.Emulation.SetVirtualTimePolicyRequest SetVirtualTimePolicy(Enyim.Iris.Protocol.Emulation.VirtualTimePolicyType Policy, double? Budget = default, int? MaxVirtualTimeTaskStarvationCount = default, Enyim.Iris.Protocol.Network.TimeSinceEpochType? InitialVirtualTime = default)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetVirtualTimePolicyRequest(Policy, Budget, MaxVirtualTimeTaskStarvationCount, InitialVirtualTime);
    }
    /// <summary>
    /// Turns on virtual time for all frames (replacing real-time with a synthetic time source) and sets<br/>
    /// the current virtual time policy.  Note this supersedes any previous time budget.<br/>
    /// </summary>
    /// <param name="Budget">
    /// If set, after this many virtual milliseconds have elapsed virtual time will be paused and a<br/>
    /// virtualTimeBudgetExpired event is sent.<br/>
    /// </param>
    /// <param name="MaxVirtualTimeTaskStarvationCount">
    /// If set this specifies the maximum number of tasks that can be run before virtual is forced<br/>
    /// forwards to prevent deadlock.<br/>
    /// </param>
    /// <param name="InitialVirtualTime">If set, base::Time::Now will be overridden to initially return this value.</param>
    [ChromeProtocol.Core.MethodName("Emulation.setVirtualTimePolicy")]
    public record SetVirtualTimePolicyRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("policy")]
      Enyim.Iris.Protocol.Emulation.VirtualTimePolicyType Policy,
      [property: System.Text.Json.Serialization.JsonPropertyName("budget")]
      double? Budget = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("maxVirtualTimeTaskStarvationCount")]
      int? MaxVirtualTimeTaskStarvationCount = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("initialVirtualTime")]
      Enyim.Iris.Protocol.Network.TimeSinceEpochType? InitialVirtualTime = default
    ) : ChromeProtocol.Core.ICommand<SetVirtualTimePolicyRequestResult>
    {
    }
    /// <param name="VirtualTimeTicksBase">Absolute timestamp at which virtual time was first enabled (up time in milliseconds).</param>
    public record SetVirtualTimePolicyRequestResult(
      [property: System.Text.Json.Serialization.JsonPropertyName("virtualTimeTicksBase")]
      double VirtualTimeTicksBase
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Overrides default host system locale with the specified one.</summary>
    /// <param name="Locale">
    /// ICU style C locale (e.g. &quot;en_US&quot;). If not specified or empty, disables the override and<br/>
    /// restores default host system locale.<br/>
    /// </param>
    public static Enyim.Iris.Protocol.Emulation.SetLocaleOverrideRequest SetLocaleOverride(string? Locale = default)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetLocaleOverrideRequest(Locale);
    }
    /// <summary>Overrides default host system locale with the specified one.</summary>
    /// <param name="Locale">
    /// ICU style C locale (e.g. &quot;en_US&quot;). If not specified or empty, disables the override and<br/>
    /// restores default host system locale.<br/>
    /// </param>
    [ChromeProtocol.Core.MethodName("Emulation.setLocaleOverride")]
    public record SetLocaleOverrideRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("locale")]
      string? Locale = default
    ) : ChromeProtocol.Core.ICommand<SetLocaleOverrideRequestResult>
    {
    }
    public record SetLocaleOverrideRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Overrides default host system timezone with the specified one.</summary>
    /// <param name="TimezoneId">
    /// The timezone identifier. List of supported timezones:<br/>
    /// https://source.chromium.org/chromium/chromium/deps/icu.git/+/faee8bc70570192d82d2978a71e2a615788597d1:source/data/misc/metaZones.txt<br/>
    /// If empty, disables the override and restores default host system timezone.<br/>
    /// </param>
    public static Enyim.Iris.Protocol.Emulation.SetTimezoneOverrideRequest SetTimezoneOverride(string TimezoneId)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetTimezoneOverrideRequest(TimezoneId);
    }
    /// <summary>Overrides default host system timezone with the specified one.</summary>
    /// <param name="TimezoneId">
    /// The timezone identifier. List of supported timezones:<br/>
    /// https://source.chromium.org/chromium/chromium/deps/icu.git/+/faee8bc70570192d82d2978a71e2a615788597d1:source/data/misc/metaZones.txt<br/>
    /// If empty, disables the override and restores default host system timezone.<br/>
    /// </param>
    [ChromeProtocol.Core.MethodName("Emulation.setTimezoneOverride")]
    public record SetTimezoneOverrideRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("timezoneId")]
      string TimezoneId
    ) : ChromeProtocol.Core.ICommand<SetTimezoneOverrideRequestResult>
    {
    }
    public record SetTimezoneOverrideRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Resizes the frame/viewport of the page. Note that this does not affect the frame&#39;s container<br/>
    /// (e.g. browser window). Can be used to produce screenshots of the specified size. Not supported<br/>
    /// on Android.<br/>
    /// </summary>
    /// <param name="Width">Frame width (DIP).</param>
    /// <param name="Height">Frame height (DIP).</param>
    [System.Obsolete("This command marked as deprecated in the corresponding CDP definition schema. It may be removed in the future releases.", false)]
    public static Enyim.Iris.Protocol.Emulation.SetVisibleSizeRequest SetVisibleSize(int Width, int Height)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetVisibleSizeRequest(Width, Height);
    }
    /// <summary>
    /// Resizes the frame/viewport of the page. Note that this does not affect the frame&#39;s container<br/>
    /// (e.g. browser window). Can be used to produce screenshots of the specified size. Not supported<br/>
    /// on Android.<br/>
    /// </summary>
    /// <param name="Width">Frame width (DIP).</param>
    /// <param name="Height">Frame height (DIP).</param>
    [ChromeProtocol.Core.MethodName("Emulation.setVisibleSize")]
    [System.Obsolete("This command marked as deprecated in the corresponding CDP definition schema. It may be removed in the future releases.", false)]
    public record SetVisibleSizeRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("width")]
      int Width,
      [property: System.Text.Json.Serialization.JsonPropertyName("height")]
      int Height
    ) : ChromeProtocol.Core.ICommand<SetVisibleSizeRequestResult>
    {
    }
    [System.Obsolete("This command marked as deprecated in the corresponding CDP definition schema. It may be removed in the future releases.", false)]
    public record SetVisibleSizeRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <param name="ImageTypes">Image types to disable.</param>
    public static Enyim.Iris.Protocol.Emulation.SetDisabledImageTypesRequest SetDisabledImageTypes(System.Collections.Generic.IReadOnlyList<Enyim.Iris.Protocol.Emulation.DisabledImageTypeType> ImageTypes)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetDisabledImageTypesRequest(ImageTypes);
    }
    /// <param name="ImageTypes">Image types to disable.</param>
    [ChromeProtocol.Core.MethodName("Emulation.setDisabledImageTypes")]
    public record SetDisabledImageTypesRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("imageTypes")]
      System.Collections.Generic.IReadOnlyList<Enyim.Iris.Protocol.Emulation.DisabledImageTypeType> ImageTypes
    ) : ChromeProtocol.Core.ICommand<SetDisabledImageTypesRequestResult>
    {
    }
    public record SetDisabledImageTypesRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Override the value of navigator.connection.saveData</summary>
    /// <param name="DataSaverEnabled">Override value. Omitting the parameter disables the override.</param>
    public static Enyim.Iris.Protocol.Emulation.SetDataSaverOverrideRequest SetDataSaverOverride(bool? DataSaverEnabled = default)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetDataSaverOverrideRequest(DataSaverEnabled);
    }
    /// <summary>Override the value of navigator.connection.saveData</summary>
    /// <param name="DataSaverEnabled">Override value. Omitting the parameter disables the override.</param>
    [ChromeProtocol.Core.MethodName("Emulation.setDataSaverOverride")]
    public record SetDataSaverOverrideRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("dataSaverEnabled")]
      bool? DataSaverEnabled = default
    ) : ChromeProtocol.Core.ICommand<SetDataSaverOverrideRequestResult>
    {
    }
    public record SetDataSaverOverrideRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <param name="HardwareConcurrency">Hardware concurrency to report</param>
    public static Enyim.Iris.Protocol.Emulation.SetHardwareConcurrencyOverrideRequest SetHardwareConcurrencyOverride(int HardwareConcurrency)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetHardwareConcurrencyOverrideRequest(HardwareConcurrency);
    }
    /// <param name="HardwareConcurrency">Hardware concurrency to report</param>
    [ChromeProtocol.Core.MethodName("Emulation.setHardwareConcurrencyOverride")]
    public record SetHardwareConcurrencyOverrideRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("hardwareConcurrency")]
      int HardwareConcurrency
    ) : ChromeProtocol.Core.ICommand<SetHardwareConcurrencyOverrideRequestResult>
    {
    }
    public record SetHardwareConcurrencyOverrideRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Allows overriding user agent with the given string.<br/>
    /// `userAgentMetadata` must be set for Client Hint headers to be sent.<br/>
    /// </summary>
    /// <param name="UserAgent">User agent to use.</param>
    /// <param name="AcceptLanguage">Browser language to emulate.</param>
    /// <param name="Platform">The platform navigator.platform should return.</param>
    /// <param name="UserAgentMetadata">To be sent in Sec-CH-UA-* headers and returned in navigator.userAgentData</param>
    public static Enyim.Iris.Protocol.Emulation.SetUserAgentOverrideRequest SetUserAgentOverride(string UserAgent, string? AcceptLanguage = default, string? Platform = default, Enyim.Iris.Protocol.Emulation.UserAgentMetadataType? UserAgentMetadata = default)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetUserAgentOverrideRequest(UserAgent, AcceptLanguage, Platform, UserAgentMetadata);
    }
    /// <summary>
    /// Allows overriding user agent with the given string.<br/>
    /// `userAgentMetadata` must be set for Client Hint headers to be sent.<br/>
    /// </summary>
    /// <param name="UserAgent">User agent to use.</param>
    /// <param name="AcceptLanguage">Browser language to emulate.</param>
    /// <param name="Platform">The platform navigator.platform should return.</param>
    /// <param name="UserAgentMetadata">To be sent in Sec-CH-UA-* headers and returned in navigator.userAgentData</param>
    [ChromeProtocol.Core.MethodName("Emulation.setUserAgentOverride")]
    public record SetUserAgentOverrideRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("userAgent")]
      string UserAgent,
      [property: System.Text.Json.Serialization.JsonPropertyName("acceptLanguage")]
      string? AcceptLanguage = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("platform")]
      string? Platform = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("userAgentMetadata")]
      Enyim.Iris.Protocol.Emulation.UserAgentMetadataType? UserAgentMetadata = default
    ) : ChromeProtocol.Core.ICommand<SetUserAgentOverrideRequestResult>
    {
    }
    public record SetUserAgentOverrideRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Allows overriding the automation flag.</summary>
    /// <param name="Enabled">Whether the override should be enabled.</param>
    public static Enyim.Iris.Protocol.Emulation.SetAutomationOverrideRequest SetAutomationOverride(bool Enabled)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetAutomationOverrideRequest(Enabled);
    }
    /// <summary>Allows overriding the automation flag.</summary>
    /// <param name="Enabled">Whether the override should be enabled.</param>
    [ChromeProtocol.Core.MethodName("Emulation.setAutomationOverride")]
    public record SetAutomationOverrideRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("enabled")]
      bool Enabled
    ) : ChromeProtocol.Core.ICommand<SetAutomationOverrideRequestResult>
    {
    }
    public record SetAutomationOverrideRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Allows overriding the difference between the small and large viewport sizes, which determine the<br/>
    /// value of the `svh` and `lvh` unit, respectively. Only supported for top-level frames.<br/>
    /// </summary>
    /// <param name="Difference">
    /// This will cause an element of size 100svh to be `difference` pixels smaller than an element<br/>
    /// of size 100lvh.<br/>
    /// </param>
    public static Enyim.Iris.Protocol.Emulation.SetSmallViewportHeightDifferenceOverrideRequest SetSmallViewportHeightDifferenceOverride(int Difference)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetSmallViewportHeightDifferenceOverrideRequest(Difference);
    }
    /// <summary>
    /// Allows overriding the difference between the small and large viewport sizes, which determine the<br/>
    /// value of the `svh` and `lvh` unit, respectively. Only supported for top-level frames.<br/>
    /// </summary>
    /// <param name="Difference">
    /// This will cause an element of size 100svh to be `difference` pixels smaller than an element<br/>
    /// of size 100lvh.<br/>
    /// </param>
    [ChromeProtocol.Core.MethodName("Emulation.setSmallViewportHeightDifferenceOverride")]
    public record SetSmallViewportHeightDifferenceOverrideRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("difference")]
      int Difference
    ) : ChromeProtocol.Core.ICommand<SetSmallViewportHeightDifferenceOverrideRequestResult>
    {
    }
    public record SetSmallViewportHeightDifferenceOverrideRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Returns device&#39;s screen configuration. In headful mode, the physical screens configuration is returned,<br/>
    /// whereas in headless mode, a virtual headless screen configuration is provided instead.<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.Emulation.GetScreenInfosRequest GetScreenInfos()    
    {
      return new Enyim.Iris.Protocol.Emulation.GetScreenInfosRequest();
    }
    /// <summary>
    /// Returns device&#39;s screen configuration. In headful mode, the physical screens configuration is returned,<br/>
    /// whereas in headless mode, a virtual headless screen configuration is provided instead.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("Emulation.getScreenInfos")]
    public record GetScreenInfosRequest() : ChromeProtocol.Core.ICommand<GetScreenInfosRequestResult>
    {
    }
    public record GetScreenInfosRequestResult(
      [property: System.Text.Json.Serialization.JsonPropertyName("screenInfos")]
      System.Collections.Generic.IReadOnlyList<Enyim.Iris.Protocol.Emulation.ScreenInfoType> ScreenInfos
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Add a new screen to the device. Only supported in headless mode.</summary>
    /// <param name="Left">Offset of the left edge of the screen in pixels.</param>
    /// <param name="Top">Offset of the top edge of the screen in pixels.</param>
    /// <param name="Width">The width of the screen in pixels.</param>
    /// <param name="Height">The height of the screen in pixels.</param>
    /// <param name="WorkAreaInsets">Specifies the screen&#39;s work area. Default is entire screen.</param>
    /// <param name="DevicePixelRatio">Specifies the screen&#39;s device pixel ratio. Default is 1.</param>
    /// <param name="Rotation">Specifies the screen&#39;s rotation angle. Available values are 0, 90, 180 and 270. Default is 0.</param>
    /// <param name="ColorDepth">Specifies the screen&#39;s color depth in bits. Default is 24.</param>
    /// <param name="Label">Specifies the descriptive label for the screen. Default is none.</param>
    /// <param name="IsInternal">Indicates whether the screen is internal to the device or external, attached to the device. Default is false.</param>
    public static Enyim.Iris.Protocol.Emulation.AddScreenRequest AddScreen(int Left, int Top, int Width, int Height, Enyim.Iris.Protocol.Emulation.WorkAreaInsetsType? WorkAreaInsets = default, double? DevicePixelRatio = default, int? Rotation = default, int? ColorDepth = default, string? Label = default, bool? IsInternal = default)    
    {
      return new Enyim.Iris.Protocol.Emulation.AddScreenRequest(Left, Top, Width, Height, WorkAreaInsets, DevicePixelRatio, Rotation, ColorDepth, Label, IsInternal);
    }
    /// <summary>Add a new screen to the device. Only supported in headless mode.</summary>
    /// <param name="Left">Offset of the left edge of the screen in pixels.</param>
    /// <param name="Top">Offset of the top edge of the screen in pixels.</param>
    /// <param name="Width">The width of the screen in pixels.</param>
    /// <param name="Height">The height of the screen in pixels.</param>
    /// <param name="WorkAreaInsets">Specifies the screen&#39;s work area. Default is entire screen.</param>
    /// <param name="DevicePixelRatio">Specifies the screen&#39;s device pixel ratio. Default is 1.</param>
    /// <param name="Rotation">Specifies the screen&#39;s rotation angle. Available values are 0, 90, 180 and 270. Default is 0.</param>
    /// <param name="ColorDepth">Specifies the screen&#39;s color depth in bits. Default is 24.</param>
    /// <param name="Label">Specifies the descriptive label for the screen. Default is none.</param>
    /// <param name="IsInternal">Indicates whether the screen is internal to the device or external, attached to the device. Default is false.</param>
    [ChromeProtocol.Core.MethodName("Emulation.addScreen")]
    public record AddScreenRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("left")]
      int Left,
      [property: System.Text.Json.Serialization.JsonPropertyName("top")]
      int Top,
      [property: System.Text.Json.Serialization.JsonPropertyName("width")]
      int Width,
      [property: System.Text.Json.Serialization.JsonPropertyName("height")]
      int Height,
      [property: System.Text.Json.Serialization.JsonPropertyName("workAreaInsets")]
      Enyim.Iris.Protocol.Emulation.WorkAreaInsetsType? WorkAreaInsets = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("devicePixelRatio")]
      double? DevicePixelRatio = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("rotation")]
      int? Rotation = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("colorDepth")]
      int? ColorDepth = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("label")]
      string? Label = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("isInternal")]
      bool? IsInternal = default
    ) : ChromeProtocol.Core.ICommand<AddScreenRequestResult>
    {
    }
    public record AddScreenRequestResult(
      [property: System.Text.Json.Serialization.JsonPropertyName("screenInfo")]
      Enyim.Iris.Protocol.Emulation.ScreenInfoType ScreenInfo
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Updates specified screen parameters. Only supported in headless mode.</summary>
    /// <param name="ScreenId">Target screen identifier.</param>
    /// <param name="Left">Offset of the left edge of the screen in pixels.</param>
    /// <param name="Top">Offset of the top edge of the screen in pixels.</param>
    /// <param name="Width">The width of the screen in pixels.</param>
    /// <param name="Height">The height of the screen in pixels.</param>
    /// <param name="WorkAreaInsets">Specifies the screen&#39;s work area.</param>
    /// <param name="DevicePixelRatio">Specifies the screen&#39;s device pixel ratio.</param>
    /// <param name="Rotation">Specifies the screen&#39;s rotation angle. Available values are 0, 90, 180 and 270.</param>
    /// <param name="ColorDepth">Specifies the screen&#39;s color depth in bits.</param>
    /// <param name="Label">Specifies the descriptive label for the screen.</param>
    /// <param name="IsInternal">Indicates whether the screen is internal to the device or external, attached to the device. Default is false.</param>
    public static Enyim.Iris.Protocol.Emulation.UpdateScreenRequest UpdateScreen(Enyim.Iris.Protocol.Emulation.ScreenIdType ScreenId, int? Left = default, int? Top = default, int? Width = default, int? Height = default, Enyim.Iris.Protocol.Emulation.WorkAreaInsetsType? WorkAreaInsets = default, double? DevicePixelRatio = default, int? Rotation = default, int? ColorDepth = default, string? Label = default, bool? IsInternal = default)    
    {
      return new Enyim.Iris.Protocol.Emulation.UpdateScreenRequest(ScreenId, Left, Top, Width, Height, WorkAreaInsets, DevicePixelRatio, Rotation, ColorDepth, Label, IsInternal);
    }
    /// <summary>Updates specified screen parameters. Only supported in headless mode.</summary>
    /// <param name="ScreenId">Target screen identifier.</param>
    /// <param name="Left">Offset of the left edge of the screen in pixels.</param>
    /// <param name="Top">Offset of the top edge of the screen in pixels.</param>
    /// <param name="Width">The width of the screen in pixels.</param>
    /// <param name="Height">The height of the screen in pixels.</param>
    /// <param name="WorkAreaInsets">Specifies the screen&#39;s work area.</param>
    /// <param name="DevicePixelRatio">Specifies the screen&#39;s device pixel ratio.</param>
    /// <param name="Rotation">Specifies the screen&#39;s rotation angle. Available values are 0, 90, 180 and 270.</param>
    /// <param name="ColorDepth">Specifies the screen&#39;s color depth in bits.</param>
    /// <param name="Label">Specifies the descriptive label for the screen.</param>
    /// <param name="IsInternal">Indicates whether the screen is internal to the device or external, attached to the device. Default is false.</param>
    [ChromeProtocol.Core.MethodName("Emulation.updateScreen")]
    public record UpdateScreenRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("screenId")]
      Enyim.Iris.Protocol.Emulation.ScreenIdType ScreenId,
      [property: System.Text.Json.Serialization.JsonPropertyName("left")]
      int? Left = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("top")]
      int? Top = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("width")]
      int? Width = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("height")]
      int? Height = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("workAreaInsets")]
      Enyim.Iris.Protocol.Emulation.WorkAreaInsetsType? WorkAreaInsets = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("devicePixelRatio")]
      double? DevicePixelRatio = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("rotation")]
      int? Rotation = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("colorDepth")]
      int? ColorDepth = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("label")]
      string? Label = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("isInternal")]
      bool? IsInternal = default
    ) : ChromeProtocol.Core.ICommand<UpdateScreenRequestResult>
    {
    }
    public record UpdateScreenRequestResult(
      [property: System.Text.Json.Serialization.JsonPropertyName("screenInfo")]
      Enyim.Iris.Protocol.Emulation.ScreenInfoType ScreenInfo
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Remove screen from the device. Only supported in headless mode.</summary>
    public static Enyim.Iris.Protocol.Emulation.RemoveScreenRequest RemoveScreen(Enyim.Iris.Protocol.Emulation.ScreenIdType ScreenId)    
    {
      return new Enyim.Iris.Protocol.Emulation.RemoveScreenRequest(ScreenId);
    }
    /// <summary>Remove screen from the device. Only supported in headless mode.</summary>
    [ChromeProtocol.Core.MethodName("Emulation.removeScreen")]
    public record RemoveScreenRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("screenId")]
      Enyim.Iris.Protocol.Emulation.ScreenIdType ScreenId
    ) : ChromeProtocol.Core.ICommand<RemoveScreenRequestResult>
    {
    }
    public record RemoveScreenRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Set primary screen. Only supported in headless mode.<br/>
    /// Note that this changes the coordinate system origin to the top-left<br/>
    /// of the new primary screen, updating the bounds and work areas<br/>
    /// of all existing screens accordingly.<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.Emulation.SetPrimaryScreenRequest SetPrimaryScreen(Enyim.Iris.Protocol.Emulation.ScreenIdType ScreenId)    
    {
      return new Enyim.Iris.Protocol.Emulation.SetPrimaryScreenRequest(ScreenId);
    }
    /// <summary>
    /// Set primary screen. Only supported in headless mode.<br/>
    /// Note that this changes the coordinate system origin to the top-left<br/>
    /// of the new primary screen, updating the bounds and work areas<br/>
    /// of all existing screens accordingly.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("Emulation.setPrimaryScreen")]
    public record SetPrimaryScreenRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("screenId")]
      Enyim.Iris.Protocol.Emulation.ScreenIdType ScreenId
    ) : ChromeProtocol.Core.ICommand<SetPrimaryScreenRequestResult>
    {
    }
    public record SetPrimaryScreenRequestResult() : ChromeProtocol.Core.IType
    {
    }
  }
}
