// <auto-generated />
#nullable enable

namespace Enyim.Iris.Protocol
{
  public static partial class Storage
  {
    [System.Text.Json.Serialization.JsonConverter(typeof(ChromeProtocol.Core.PrimitiveTypeConverter))]
    public record SerializedStorageKeyType(
      string Value
    ) : ChromeProtocol.Core.PrimitiveType<string>(Value)
    {
    }
    /// <summary>Enum of possible storage types.</summary>
    [System.Text.Json.Serialization.JsonConverter(typeof(ChromeProtocol.Core.PrimitiveTypeConverter))]
    public record StorageTypeType(
      string Value
    ) : ChromeProtocol.Core.PrimitiveType<string>(Value)
    {
    }
    /// <summary>Usage for a storage type.</summary>
    /// <param name="StorageType">Name of storage type.</param>
    /// <param name="Usage">Storage usage (bytes).</param>
    public record UsageForTypeType(
      [property: System.Text.Json.Serialization.JsonPropertyName("storageType")]
      Enyim.Iris.Protocol.Storage.StorageTypeType StorageType,
      [property: System.Text.Json.Serialization.JsonPropertyName("usage")]
      double Usage
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Pair of issuer origin and number of available (signed, but not used) Trust<br/>
    /// Tokens from that issuer.<br/>
    /// </summary>
    public record TrustTokensType(
      [property: System.Text.Json.Serialization.JsonPropertyName("issuerOrigin")]
      string IssuerOrigin,
      [property: System.Text.Json.Serialization.JsonPropertyName("count")]
      double Count
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Protected audience interest group auction identifier.</summary>
    [System.Text.Json.Serialization.JsonConverter(typeof(ChromeProtocol.Core.PrimitiveTypeConverter))]
    public record InterestGroupAuctionIdType(
      string Value
    ) : ChromeProtocol.Core.PrimitiveType<string>(Value)
    {
    }
    /// <summary>Enum of interest group access types.</summary>
    [System.Text.Json.Serialization.JsonConverter(typeof(ChromeProtocol.Core.PrimitiveTypeConverter))]
    public record InterestGroupAccessTypeType(
      string Value
    ) : ChromeProtocol.Core.PrimitiveType<string>(Value)
    {
    }
    /// <summary>Enum of auction events.</summary>
    [System.Text.Json.Serialization.JsonConverter(typeof(ChromeProtocol.Core.PrimitiveTypeConverter))]
    public record InterestGroupAuctionEventTypeType(
      string Value
    ) : ChromeProtocol.Core.PrimitiveType<string>(Value)
    {
    }
    /// <summary>Enum of network fetches auctions can do.</summary>
    [System.Text.Json.Serialization.JsonConverter(typeof(ChromeProtocol.Core.PrimitiveTypeConverter))]
    public record InterestGroupAuctionFetchTypeType(
      string Value
    ) : ChromeProtocol.Core.PrimitiveType<string>(Value)
    {
    }
    /// <summary>Enum of shared storage access scopes.</summary>
    [System.Text.Json.Serialization.JsonConverter(typeof(ChromeProtocol.Core.PrimitiveTypeConverter))]
    public record SharedStorageAccessScopeType(
      string Value
    ) : ChromeProtocol.Core.PrimitiveType<string>(Value)
    {
    }
    /// <summary>Enum of shared storage access methods.</summary>
    [System.Text.Json.Serialization.JsonConverter(typeof(ChromeProtocol.Core.PrimitiveTypeConverter))]
    public record SharedStorageAccessMethodType(
      string Value
    ) : ChromeProtocol.Core.PrimitiveType<string>(Value)
    {
    }
    /// <summary>Struct for a single key-value pair in an origin&#39;s shared storage.</summary>
    public record SharedStorageEntryType(
      [property: System.Text.Json.Serialization.JsonPropertyName("key")]
      string Key,
      [property: System.Text.Json.Serialization.JsonPropertyName("value")]
      string Value
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Details for an origin&#39;s shared storage.</summary>
    /// <param name="CreationTime">Time when the origin&#39;s shared storage was last created.</param>
    /// <param name="Length">Number of key-value pairs stored in origin&#39;s shared storage.</param>
    /// <param name="RemainingBudget">Current amount of bits of entropy remaining in the navigation budget.</param>
    /// <param name="BytesUsed">
    /// Total number of bytes stored as key-value pairs in origin&#39;s shared<br/>
    /// storage.<br/>
    /// </param>
    public record SharedStorageMetadataType(
      [property: System.Text.Json.Serialization.JsonPropertyName("creationTime")]
      Enyim.Iris.Protocol.Network.TimeSinceEpochType CreationTime,
      [property: System.Text.Json.Serialization.JsonPropertyName("length")]
      int Length,
      [property: System.Text.Json.Serialization.JsonPropertyName("remainingBudget")]
      double RemainingBudget,
      [property: System.Text.Json.Serialization.JsonPropertyName("bytesUsed")]
      int BytesUsed
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Represents a dictionary object passed in as privateAggregationConfig to<br/>
    /// run or selectURL.<br/>
    /// </summary>
    /// <param name="FilteringIdMaxBytes">Configures the maximum size allowed for filtering IDs.</param>
    /// <param name="AggregationCoordinatorOrigin">The chosen aggregation service deployment.</param>
    /// <param name="ContextId">The context ID provided.</param>
    /// <param name="MaxContributions">The limit on the number of contributions in the final report.</param>
    public record SharedStoragePrivateAggregationConfigType(
      [property: System.Text.Json.Serialization.JsonPropertyName("filteringIdMaxBytes")]
      int FilteringIdMaxBytes,
      [property: System.Text.Json.Serialization.JsonPropertyName("aggregationCoordinatorOrigin")]
      string? AggregationCoordinatorOrigin = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("contextId")]
      string? ContextId = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("maxContributions")]
      int? MaxContributions = default
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Pair of reporting metadata details for a candidate URL for `selectURL()`.</summary>
    public record SharedStorageReportingMetadataType(
      [property: System.Text.Json.Serialization.JsonPropertyName("eventType")]
      string EventType,
      [property: System.Text.Json.Serialization.JsonPropertyName("reportingUrl")]
      string ReportingUrl
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Bundles a candidate URL with its reporting metadata.</summary>
    /// <param name="Url">Spec of candidate URL.</param>
    /// <param name="ReportingMetadata">Any associated reporting metadata.</param>
    public record SharedStorageUrlWithMetadataType(
      [property: System.Text.Json.Serialization.JsonPropertyName("url")]
      string Url,
      [property: System.Text.Json.Serialization.JsonPropertyName("reportingMetadata")]
      System.Collections.Generic.IReadOnlyList<Enyim.Iris.Protocol.Storage.SharedStorageReportingMetadataType> ReportingMetadata
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Bundles the parameters for shared storage access events whose<br/>
    /// presence/absence can vary according to SharedStorageAccessType.<br/>
    /// </summary>
    /// <param name="ScriptSourceUrl">
    /// Spec of the module script URL.<br/>
    /// Present only for SharedStorageAccessMethods: addModule and<br/>
    /// createWorklet.<br/>
    /// </param>
    /// <param name="DataOrigin">
    /// String denoting &quot;context-origin&quot;, &quot;script-origin&quot;, or a custom<br/>
    /// origin to be used as the worklet&#39;s data origin.<br/>
    /// Present only for SharedStorageAccessMethod: createWorklet.<br/>
    /// </param>
    /// <param name="OperationName">
    /// Name of the registered operation to be run.<br/>
    /// Present only for SharedStorageAccessMethods: run and selectURL.<br/>
    /// </param>
    /// <param name="OperationId">
    /// ID of the operation call.<br/>
    /// Present only for SharedStorageAccessMethods: run and selectURL.<br/>
    /// </param>
    /// <param name="KeepAlive">
    /// Whether or not to keep the worket alive for future run or selectURL<br/>
    /// calls.<br/>
    /// Present only for SharedStorageAccessMethods: run and selectURL.<br/>
    /// </param>
    /// <param name="PrivateAggregationConfig">
    /// Configures the private aggregation options.<br/>
    /// Present only for SharedStorageAccessMethods: run and selectURL.<br/>
    /// </param>
    /// <param name="SerializedData">
    /// The operation&#39;s serialized data in bytes (converted to a string).<br/>
    /// Present only for SharedStorageAccessMethods: run and selectURL.<br/>
    /// TODO(crbug.com/401011862): Consider updating this parameter to binary.<br/>
    /// </param>
    /// <param name="UrlsWithMetadata">
    /// Array of candidate URLs&#39; specs, along with any associated metadata.<br/>
    /// Present only for SharedStorageAccessMethod: selectURL.<br/>
    /// </param>
    /// <param name="UrnUuid">
    /// Spec of the URN:UUID generated for a selectURL call.<br/>
    /// Present only for SharedStorageAccessMethod: selectURL.<br/>
    /// </param>
    /// <param name="Key">
    /// Key for a specific entry in an origin&#39;s shared storage.<br/>
    /// Present only for SharedStorageAccessMethods: set, append, delete, and<br/>
    /// get.<br/>
    /// </param>
    /// <param name="Value">
    /// Value for a specific entry in an origin&#39;s shared storage.<br/>
    /// Present only for SharedStorageAccessMethods: set and append.<br/>
    /// </param>
    /// <param name="IgnoreIfPresent">
    /// Whether or not to set an entry for a key if that key is already present.<br/>
    /// Present only for SharedStorageAccessMethod: set.<br/>
    /// </param>
    /// <param name="WorkletOrdinal">
    /// A number denoting the (0-based) order of the worklet&#39;s<br/>
    /// creation relative to all other shared storage worklets created by<br/>
    /// documents using the current storage partition.<br/>
    /// Present only for SharedStorageAccessMethods: addModule, createWorklet.<br/>
    /// </param>
    /// <param name="WorkletTargetId">
    /// Hex representation of the DevTools token used as the TargetID for the<br/>
    /// associated shared storage worklet.<br/>
    /// Present only for SharedStorageAccessMethods: addModule, createWorklet,<br/>
    /// run, selectURL, and any other SharedStorageAccessMethod when the<br/>
    /// SharedStorageAccessScope is sharedStorageWorklet.<br/>
    /// </param>
    /// <param name="WithLock">
    /// Name of the lock to be acquired, if present.<br/>
    /// Optionally present only for SharedStorageAccessMethods: batchUpdate,<br/>
    /// set, append, delete, and clear.<br/>
    /// </param>
    /// <param name="BatchUpdateId">
    /// If the method has been called as part of a batchUpdate, then this<br/>
    /// number identifies the batch to which it belongs.<br/>
    /// Optionally present only for SharedStorageAccessMethods:<br/>
    /// batchUpdate (required), set, append, delete, and clear.<br/>
    /// </param>
    /// <param name="BatchSize">
    /// Number of modifier methods sent in batch.<br/>
    /// Present only for SharedStorageAccessMethod: batchUpdate.<br/>
    /// </param>
    public record SharedStorageAccessParamsType(
      [property: System.Text.Json.Serialization.JsonPropertyName("scriptSourceUrl")]
      string? ScriptSourceUrl = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("dataOrigin")]
      string? DataOrigin = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("operationName")]
      string? OperationName = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("operationId")]
      string? OperationId = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("keepAlive")]
      bool? KeepAlive = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("privateAggregationConfig")]
      Enyim.Iris.Protocol.Storage.SharedStoragePrivateAggregationConfigType? PrivateAggregationConfig = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("serializedData")]
      string? SerializedData = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("urlsWithMetadata")]
      System.Collections.Generic.IReadOnlyList<Enyim.Iris.Protocol.Storage.SharedStorageUrlWithMetadataType>? UrlsWithMetadata = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("urnUuid")]
      string? UrnUuid = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("key")]
      string? Key = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("value")]
      string? Value = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("ignoreIfPresent")]
      bool? IgnoreIfPresent = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("workletOrdinal")]
      int? WorkletOrdinal = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("workletTargetId")]
      Enyim.Iris.Protocol.Target.TargetIDType? WorkletTargetId = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("withLock")]
      string? WithLock = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("batchUpdateId")]
      string? BatchUpdateId = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("batchSize")]
      int? BatchSize = default
    ) : ChromeProtocol.Core.IType
    {
    }
    [System.Text.Json.Serialization.JsonConverter(typeof(ChromeProtocol.Core.PrimitiveTypeConverter))]
    public record StorageBucketsDurabilityType(
      string Value
    ) : ChromeProtocol.Core.PrimitiveType<string>(Value)
    {
    }
    /// <param name="Name">If not specified, it is the default bucket of the storageKey.</param>
    public record StorageBucketType(
      [property: System.Text.Json.Serialization.JsonPropertyName("storageKey")]
      Enyim.Iris.Protocol.Storage.SerializedStorageKeyType StorageKey,
      [property: System.Text.Json.Serialization.JsonPropertyName("name")]
      string? Name = default
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <param name="Quota">Storage quota (bytes).</param>
    public record StorageBucketInfoType(
      [property: System.Text.Json.Serialization.JsonPropertyName("bucket")]
      Enyim.Iris.Protocol.Storage.StorageBucketType Bucket,
      [property: System.Text.Json.Serialization.JsonPropertyName("id")]
      string Id,
      [property: System.Text.Json.Serialization.JsonPropertyName("expiration")]
      Enyim.Iris.Protocol.Network.TimeSinceEpochType Expiration,
      [property: System.Text.Json.Serialization.JsonPropertyName("quota")]
      double Quota,
      [property: System.Text.Json.Serialization.JsonPropertyName("persistent")]
      bool Persistent,
      [property: System.Text.Json.Serialization.JsonPropertyName("durability")]
      Enyim.Iris.Protocol.Storage.StorageBucketsDurabilityType Durability
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>A single Related Website Set object.</summary>
    /// <param name="PrimarySites">The primary site of this set, along with the ccTLDs if there is any.</param>
    /// <param name="AssociatedSites">The associated sites of this set, along with the ccTLDs if there is any.</param>
    /// <param name="ServiceSites">The service sites of this set, along with the ccTLDs if there is any.</param>
    public record RelatedWebsiteSetType(
      [property: System.Text.Json.Serialization.JsonPropertyName("primarySites")]
      System.Collections.Generic.IReadOnlyList<string> PrimarySites,
      [property: System.Text.Json.Serialization.JsonPropertyName("associatedSites")]
      System.Collections.Generic.IReadOnlyList<string> AssociatedSites,
      [property: System.Text.Json.Serialization.JsonPropertyName("serviceSites")]
      System.Collections.Generic.IReadOnlyList<string> ServiceSites
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>A cache&#39;s contents have been modified.</summary>
    /// <param name="Origin">Origin to update.</param>
    /// <param name="StorageKey">Storage key to update.</param>
    /// <param name="BucketId">Storage bucket to update.</param>
    /// <param name="CacheName">Name of cache in origin.</param>
    [ChromeProtocol.Core.MethodName("Storage.cacheStorageContentUpdated")]
    public record CacheStorageContentUpdated(
      [property: System.Text.Json.Serialization.JsonPropertyName("origin")]
      string Origin,
      [property: System.Text.Json.Serialization.JsonPropertyName("storageKey")]
      string StorageKey,
      [property: System.Text.Json.Serialization.JsonPropertyName("bucketId")]
      string BucketId,
      [property: System.Text.Json.Serialization.JsonPropertyName("cacheName")]
      string CacheName
    ) : ChromeProtocol.Core.IEvent
    {
    }
    /// <summary>A cache has been added/deleted.</summary>
    /// <param name="Origin">Origin to update.</param>
    /// <param name="StorageKey">Storage key to update.</param>
    /// <param name="BucketId">Storage bucket to update.</param>
    [ChromeProtocol.Core.MethodName("Storage.cacheStorageListUpdated")]
    public record CacheStorageListUpdated(
      [property: System.Text.Json.Serialization.JsonPropertyName("origin")]
      string Origin,
      [property: System.Text.Json.Serialization.JsonPropertyName("storageKey")]
      string StorageKey,
      [property: System.Text.Json.Serialization.JsonPropertyName("bucketId")]
      string BucketId
    ) : ChromeProtocol.Core.IEvent
    {
    }
    /// <summary>The origin&#39;s IndexedDB object store has been modified.</summary>
    /// <param name="Origin">Origin to update.</param>
    /// <param name="StorageKey">Storage key to update.</param>
    /// <param name="BucketId">Storage bucket to update.</param>
    /// <param name="DatabaseName">Database to update.</param>
    /// <param name="ObjectStoreName">ObjectStore to update.</param>
    [ChromeProtocol.Core.MethodName("Storage.indexedDBContentUpdated")]
    public record IndexedDBContentUpdated(
      [property: System.Text.Json.Serialization.JsonPropertyName("origin")]
      string Origin,
      [property: System.Text.Json.Serialization.JsonPropertyName("storageKey")]
      string StorageKey,
      [property: System.Text.Json.Serialization.JsonPropertyName("bucketId")]
      string BucketId,
      [property: System.Text.Json.Serialization.JsonPropertyName("databaseName")]
      string DatabaseName,
      [property: System.Text.Json.Serialization.JsonPropertyName("objectStoreName")]
      string ObjectStoreName
    ) : ChromeProtocol.Core.IEvent
    {
    }
    /// <summary>The origin&#39;s IndexedDB database list has been modified.</summary>
    /// <param name="Origin">Origin to update.</param>
    /// <param name="StorageKey">Storage key to update.</param>
    /// <param name="BucketId">Storage bucket to update.</param>
    [ChromeProtocol.Core.MethodName("Storage.indexedDBListUpdated")]
    public record IndexedDBListUpdated(
      [property: System.Text.Json.Serialization.JsonPropertyName("origin")]
      string Origin,
      [property: System.Text.Json.Serialization.JsonPropertyName("storageKey")]
      string StorageKey,
      [property: System.Text.Json.Serialization.JsonPropertyName("bucketId")]
      string BucketId
    ) : ChromeProtocol.Core.IEvent
    {
    }
    /// <summary>
    /// One of the interest groups was accessed. Note that these events are global<br/>
    /// to all targets sharing an interest group store.<br/>
    /// </summary>
    /// <param name="ComponentSellerOrigin">
    /// For topLevelBid/topLevelAdditionalBid, and when appropriate,<br/>
    /// win and additionalBidWin<br/>
    /// </param>
    /// <param name="Bid">For bid or somethingBid event, if done locally and not on a server.</param>
    /// <param name="UniqueAuctionId">For non-global events --- links to interestGroupAuctionEvent</param>
    [ChromeProtocol.Core.MethodName("Storage.interestGroupAccessed")]
    public record InterestGroupAccessed(
      [property: System.Text.Json.Serialization.JsonPropertyName("accessTime")]
      Enyim.Iris.Protocol.Network.TimeSinceEpochType AccessTime,
      [property: System.Text.Json.Serialization.JsonPropertyName("type")]
      Enyim.Iris.Protocol.Storage.InterestGroupAccessTypeType Type,
      [property: System.Text.Json.Serialization.JsonPropertyName("ownerOrigin")]
      string OwnerOrigin,
      [property: System.Text.Json.Serialization.JsonPropertyName("name")]
      string Name,
      [property: System.Text.Json.Serialization.JsonPropertyName("componentSellerOrigin")]
      string? ComponentSellerOrigin = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("bid")]
      double? Bid = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("bidCurrency")]
      string? BidCurrency = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("uniqueAuctionId")]
      Enyim.Iris.Protocol.Storage.InterestGroupAuctionIdType? UniqueAuctionId = default
    ) : ChromeProtocol.Core.IEvent
    {
    }
    /// <summary>
    /// An auction involving interest groups is taking place. These events are<br/>
    /// target-specific.<br/>
    /// </summary>
    /// <param name="ParentAuctionId">Set for child auctions.</param>
    /// <param name="AuctionConfig">Set for started and configResolved</param>
    [ChromeProtocol.Core.MethodName("Storage.interestGroupAuctionEventOccurred")]
    public record InterestGroupAuctionEventOccurred(
      [property: System.Text.Json.Serialization.JsonPropertyName("eventTime")]
      Enyim.Iris.Protocol.Network.TimeSinceEpochType EventTime,
      [property: System.Text.Json.Serialization.JsonPropertyName("type")]
      Enyim.Iris.Protocol.Storage.InterestGroupAuctionEventTypeType Type,
      [property: System.Text.Json.Serialization.JsonPropertyName("uniqueAuctionId")]
      Enyim.Iris.Protocol.Storage.InterestGroupAuctionIdType UniqueAuctionId,
      [property: System.Text.Json.Serialization.JsonPropertyName("parentAuctionId")]
      Enyim.Iris.Protocol.Storage.InterestGroupAuctionIdType? ParentAuctionId = default,
      [property: System.Text.Json.Serialization.JsonPropertyName("auctionConfig")]
      System.Text.Json.Nodes.JsonObject? AuctionConfig = default
    ) : ChromeProtocol.Core.IEvent
    {
    }
    /// <summary>
    /// Specifies which auctions a particular network fetch may be related to, and<br/>
    /// in what role. Note that it is not ordered with respect to<br/>
    /// Network.requestWillBeSent (but will happen before loadingFinished<br/>
    /// loadingFailed).<br/>
    /// </summary>
    /// <param name="Auctions">
    /// This is the set of the auctions using the worklet that issued this<br/>
    /// request.  In the case of trusted signals, it&#39;s possible that only some of<br/>
    /// them actually care about the keys being queried.<br/>
    /// </param>
    [ChromeProtocol.Core.MethodName("Storage.interestGroupAuctionNetworkRequestCreated")]
    public record InterestGroupAuctionNetworkRequestCreated(
      [property: System.Text.Json.Serialization.JsonPropertyName("type")]
      Enyim.Iris.Protocol.Storage.InterestGroupAuctionFetchTypeType Type,
      [property: System.Text.Json.Serialization.JsonPropertyName("requestId")]
      Enyim.Iris.Protocol.Network.RequestIdType RequestId,
      [property: System.Text.Json.Serialization.JsonPropertyName("auctions")]
      System.Collections.Generic.IReadOnlyList<Enyim.Iris.Protocol.Storage.InterestGroupAuctionIdType> Auctions
    ) : ChromeProtocol.Core.IEvent
    {
    }
    /// <summary>
    /// Shared storage was accessed by the associated page.<br/>
    /// The following parameters are included in all events.<br/>
    /// </summary>
    /// <param name="AccessTime">Time of the access.</param>
    /// <param name="Scope">Enum value indicating the access scope.</param>
    /// <param name="Method">Enum value indicating the Shared Storage API method invoked.</param>
    /// <param name="MainFrameId">DevTools Frame Token for the primary frame tree&#39;s root.</param>
    /// <param name="OwnerOrigin">Serialization of the origin owning the Shared Storage data.</param>
    /// <param name="OwnerSite">Serialization of the site owning the Shared Storage data.</param>
    /// <param name="Params">
    /// The sub-parameters wrapped by `params` are all optional and their<br/>
    /// presence/absence depends on `type`.<br/>
    /// </param>
    [ChromeProtocol.Core.MethodName("Storage.sharedStorageAccessed")]
    public record SharedStorageAccessed(
      [property: System.Text.Json.Serialization.JsonPropertyName("accessTime")]
      Enyim.Iris.Protocol.Network.TimeSinceEpochType AccessTime,
      [property: System.Text.Json.Serialization.JsonPropertyName("scope")]
      Enyim.Iris.Protocol.Storage.SharedStorageAccessScopeType Scope,
      [property: System.Text.Json.Serialization.JsonPropertyName("method")]
      Enyim.Iris.Protocol.Storage.SharedStorageAccessMethodType Method,
      [property: System.Text.Json.Serialization.JsonPropertyName("mainFrameId")]
      Enyim.Iris.Protocol.Page.FrameIdType MainFrameId,
      [property: System.Text.Json.Serialization.JsonPropertyName("ownerOrigin")]
      string OwnerOrigin,
      [property: System.Text.Json.Serialization.JsonPropertyName("ownerSite")]
      string OwnerSite,
      [property: System.Text.Json.Serialization.JsonPropertyName("params")]
      Enyim.Iris.Protocol.Storage.SharedStorageAccessParamsType Params
    ) : ChromeProtocol.Core.IEvent
    {
    }
    /// <summary>
    /// A shared storage run or selectURL operation finished its execution.<br/>
    /// The following parameters are included in all events.<br/>
    /// </summary>
    /// <param name="FinishedTime">Time that the operation finished.</param>
    /// <param name="ExecutionTime">
    /// Time, in microseconds, from start of shared storage JS API call until<br/>
    /// end of operation execution in the worklet.<br/>
    /// </param>
    /// <param name="Method">Enum value indicating the Shared Storage API method invoked.</param>
    /// <param name="OperationId">ID of the operation call.</param>
    /// <param name="WorkletTargetId">
    /// Hex representation of the DevTools token used as the TargetID for the<br/>
    /// associated shared storage worklet.<br/>
    /// </param>
    /// <param name="MainFrameId">DevTools Frame Token for the primary frame tree&#39;s root.</param>
    /// <param name="OwnerOrigin">Serialization of the origin owning the Shared Storage data.</param>
    [ChromeProtocol.Core.MethodName("Storage.sharedStorageWorkletOperationExecutionFinished")]
    public record SharedStorageWorkletOperationExecutionFinished(
      [property: System.Text.Json.Serialization.JsonPropertyName("finishedTime")]
      Enyim.Iris.Protocol.Network.TimeSinceEpochType FinishedTime,
      [property: System.Text.Json.Serialization.JsonPropertyName("executionTime")]
      int ExecutionTime,
      [property: System.Text.Json.Serialization.JsonPropertyName("method")]
      Enyim.Iris.Protocol.Storage.SharedStorageAccessMethodType Method,
      [property: System.Text.Json.Serialization.JsonPropertyName("operationId")]
      string OperationId,
      [property: System.Text.Json.Serialization.JsonPropertyName("workletTargetId")]
      Enyim.Iris.Protocol.Target.TargetIDType WorkletTargetId,
      [property: System.Text.Json.Serialization.JsonPropertyName("mainFrameId")]
      Enyim.Iris.Protocol.Page.FrameIdType MainFrameId,
      [property: System.Text.Json.Serialization.JsonPropertyName("ownerOrigin")]
      string OwnerOrigin
    ) : ChromeProtocol.Core.IEvent
    {
    }
    [ChromeProtocol.Core.MethodName("Storage.storageBucketCreatedOrUpdated")]
    public record StorageBucketCreatedOrUpdated(
      [property: System.Text.Json.Serialization.JsonPropertyName("bucketInfo")]
      Enyim.Iris.Protocol.Storage.StorageBucketInfoType BucketInfo
    ) : ChromeProtocol.Core.IEvent
    {
    }
    [ChromeProtocol.Core.MethodName("Storage.storageBucketDeleted")]
    public record StorageBucketDeleted(
      [property: System.Text.Json.Serialization.JsonPropertyName("bucketId")]
      string BucketId
    ) : ChromeProtocol.Core.IEvent
    {
    }
    /// <summary>
    /// Returns a storage key given a frame id.<br/>
    /// Deprecated. Please use Storage.getStorageKey instead.<br/>
    /// </summary>
    [System.Obsolete("This command marked as deprecated in the corresponding CDP definition schema. It may be removed in the future releases.", false)]
    public static Enyim.Iris.Protocol.Storage.GetStorageKeyForFrameRequest GetStorageKeyForFrame(Enyim.Iris.Protocol.Page.FrameIdType FrameId)    
    {
      return new Enyim.Iris.Protocol.Storage.GetStorageKeyForFrameRequest(FrameId);
    }
    /// <summary>
    /// Returns a storage key given a frame id.<br/>
    /// Deprecated. Please use Storage.getStorageKey instead.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("Storage.getStorageKeyForFrame")]
    [System.Obsolete("This command marked as deprecated in the corresponding CDP definition schema. It may be removed in the future releases.", false)]
    public record GetStorageKeyForFrameRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("frameId")]
      Enyim.Iris.Protocol.Page.FrameIdType FrameId
    ) : ChromeProtocol.Core.ICommand<GetStorageKeyForFrameRequestResult>
    {
    }
    [System.Obsolete("This command marked as deprecated in the corresponding CDP definition schema. It may be removed in the future releases.", false)]
    public record GetStorageKeyForFrameRequestResult(
      [property: System.Text.Json.Serialization.JsonPropertyName("storageKey")]
      Enyim.Iris.Protocol.Storage.SerializedStorageKeyType StorageKey
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Returns storage key for the given frame. If no frame ID is provided,<br/>
    /// the storage key of the target executing this command is returned.<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.Storage.GetStorageKeyRequest GetStorageKey(Enyim.Iris.Protocol.Page.FrameIdType? FrameId = default)    
    {
      return new Enyim.Iris.Protocol.Storage.GetStorageKeyRequest(FrameId);
    }
    /// <summary>
    /// Returns storage key for the given frame. If no frame ID is provided,<br/>
    /// the storage key of the target executing this command is returned.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("Storage.getStorageKey")]
    public record GetStorageKeyRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("frameId")]
      Enyim.Iris.Protocol.Page.FrameIdType? FrameId = default
    ) : ChromeProtocol.Core.ICommand<GetStorageKeyRequestResult>
    {
    }
    public record GetStorageKeyRequestResult(
      [property: System.Text.Json.Serialization.JsonPropertyName("storageKey")]
      Enyim.Iris.Protocol.Storage.SerializedStorageKeyType StorageKey
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Clears storage for origin.</summary>
    /// <param name="Origin">Security origin.</param>
    /// <param name="StorageTypes">Comma separated list of StorageType to clear.</param>
    public static Enyim.Iris.Protocol.Storage.ClearDataForOriginRequest ClearDataForOrigin(string Origin, string StorageTypes)    
    {
      return new Enyim.Iris.Protocol.Storage.ClearDataForOriginRequest(Origin, StorageTypes);
    }
    /// <summary>Clears storage for origin.</summary>
    /// <param name="Origin">Security origin.</param>
    /// <param name="StorageTypes">Comma separated list of StorageType to clear.</param>
    [ChromeProtocol.Core.MethodName("Storage.clearDataForOrigin")]
    public record ClearDataForOriginRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("origin")]
      string Origin,
      [property: System.Text.Json.Serialization.JsonPropertyName("storageTypes")]
      string StorageTypes
    ) : ChromeProtocol.Core.ICommand<ClearDataForOriginRequestResult>
    {
    }
    public record ClearDataForOriginRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Clears storage for storage key.</summary>
    /// <param name="StorageKey">Storage key.</param>
    /// <param name="StorageTypes">Comma separated list of StorageType to clear.</param>
    public static Enyim.Iris.Protocol.Storage.ClearDataForStorageKeyRequest ClearDataForStorageKey(string StorageKey, string StorageTypes)    
    {
      return new Enyim.Iris.Protocol.Storage.ClearDataForStorageKeyRequest(StorageKey, StorageTypes);
    }
    /// <summary>Clears storage for storage key.</summary>
    /// <param name="StorageKey">Storage key.</param>
    /// <param name="StorageTypes">Comma separated list of StorageType to clear.</param>
    [ChromeProtocol.Core.MethodName("Storage.clearDataForStorageKey")]
    public record ClearDataForStorageKeyRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("storageKey")]
      string StorageKey,
      [property: System.Text.Json.Serialization.JsonPropertyName("storageTypes")]
      string StorageTypes
    ) : ChromeProtocol.Core.ICommand<ClearDataForStorageKeyRequestResult>
    {
    }
    public record ClearDataForStorageKeyRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Returns all browser cookies.</summary>
    /// <param name="BrowserContextId">Browser context to use when called on the browser endpoint.</param>
    public static Enyim.Iris.Protocol.Storage.GetCookiesRequest GetCookies(Enyim.Iris.Protocol.Browser.BrowserContextIDType? BrowserContextId = default)    
    {
      return new Enyim.Iris.Protocol.Storage.GetCookiesRequest(BrowserContextId);
    }
    /// <summary>Returns all browser cookies.</summary>
    /// <param name="BrowserContextId">Browser context to use when called on the browser endpoint.</param>
    [ChromeProtocol.Core.MethodName("Storage.getCookies")]
    public record GetCookiesRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("browserContextId")]
      Enyim.Iris.Protocol.Browser.BrowserContextIDType? BrowserContextId = default
    ) : ChromeProtocol.Core.ICommand<GetCookiesRequestResult>
    {
    }
    /// <param name="Cookies">Array of cookie objects.</param>
    public record GetCookiesRequestResult(
      [property: System.Text.Json.Serialization.JsonPropertyName("cookies")]
      System.Collections.Generic.IReadOnlyList<Enyim.Iris.Protocol.Network.CookieType> Cookies
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Sets given cookies.</summary>
    /// <param name="Cookies">Cookies to be set.</param>
    /// <param name="BrowserContextId">Browser context to use when called on the browser endpoint.</param>
    public static Enyim.Iris.Protocol.Storage.SetCookiesRequest SetCookies(System.Collections.Generic.IReadOnlyList<Enyim.Iris.Protocol.Network.CookieParamType> Cookies, Enyim.Iris.Protocol.Browser.BrowserContextIDType? BrowserContextId = default)    
    {
      return new Enyim.Iris.Protocol.Storage.SetCookiesRequest(Cookies, BrowserContextId);
    }
    /// <summary>Sets given cookies.</summary>
    /// <param name="Cookies">Cookies to be set.</param>
    /// <param name="BrowserContextId">Browser context to use when called on the browser endpoint.</param>
    [ChromeProtocol.Core.MethodName("Storage.setCookies")]
    public record SetCookiesRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("cookies")]
      System.Collections.Generic.IReadOnlyList<Enyim.Iris.Protocol.Network.CookieParamType> Cookies,
      [property: System.Text.Json.Serialization.JsonPropertyName("browserContextId")]
      Enyim.Iris.Protocol.Browser.BrowserContextIDType? BrowserContextId = default
    ) : ChromeProtocol.Core.ICommand<SetCookiesRequestResult>
    {
    }
    public record SetCookiesRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Clears cookies.</summary>
    /// <param name="BrowserContextId">Browser context to use when called on the browser endpoint.</param>
    public static Enyim.Iris.Protocol.Storage.ClearCookiesRequest ClearCookies(Enyim.Iris.Protocol.Browser.BrowserContextIDType? BrowserContextId = default)    
    {
      return new Enyim.Iris.Protocol.Storage.ClearCookiesRequest(BrowserContextId);
    }
    /// <summary>Clears cookies.</summary>
    /// <param name="BrowserContextId">Browser context to use when called on the browser endpoint.</param>
    [ChromeProtocol.Core.MethodName("Storage.clearCookies")]
    public record ClearCookiesRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("browserContextId")]
      Enyim.Iris.Protocol.Browser.BrowserContextIDType? BrowserContextId = default
    ) : ChromeProtocol.Core.ICommand<ClearCookiesRequestResult>
    {
    }
    public record ClearCookiesRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Returns usage and quota in bytes.</summary>
    /// <param name="Origin">Security origin.</param>
    public static Enyim.Iris.Protocol.Storage.GetUsageAndQuotaRequest GetUsageAndQuota(string Origin)    
    {
      return new Enyim.Iris.Protocol.Storage.GetUsageAndQuotaRequest(Origin);
    }
    /// <summary>Returns usage and quota in bytes.</summary>
    /// <param name="Origin">Security origin.</param>
    [ChromeProtocol.Core.MethodName("Storage.getUsageAndQuota")]
    public record GetUsageAndQuotaRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("origin")]
      string Origin
    ) : ChromeProtocol.Core.ICommand<GetUsageAndQuotaRequestResult>
    {
    }
    /// <param name="Usage">Storage usage (bytes).</param>
    /// <param name="Quota">Storage quota (bytes).</param>
    /// <param name="OverrideActive">Whether or not the origin has an active storage quota override</param>
    /// <param name="UsageBreakdown">Storage usage per type (bytes).</param>
    public record GetUsageAndQuotaRequestResult(
      [property: System.Text.Json.Serialization.JsonPropertyName("usage")]
      double Usage,
      [property: System.Text.Json.Serialization.JsonPropertyName("quota")]
      double Quota,
      [property: System.Text.Json.Serialization.JsonPropertyName("overrideActive")]
      bool OverrideActive,
      [property: System.Text.Json.Serialization.JsonPropertyName("usageBreakdown")]
      System.Collections.Generic.IReadOnlyList<Enyim.Iris.Protocol.Storage.UsageForTypeType> UsageBreakdown
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Override quota for the specified origin</summary>
    /// <param name="Origin">Security origin.</param>
    /// <param name="QuotaSize">
    /// The quota size (in bytes) to override the original quota with.<br/>
    /// If this is called multiple times, the overridden quota will be equal to<br/>
    /// the quotaSize provided in the final call. If this is called without<br/>
    /// specifying a quotaSize, the quota will be reset to the default value for<br/>
    /// the specified origin. If this is called multiple times with different<br/>
    /// origins, the override will be maintained for each origin until it is<br/>
    /// disabled (called without a quotaSize).<br/>
    /// </param>
    public static Enyim.Iris.Protocol.Storage.OverrideQuotaForOriginRequest OverrideQuotaForOrigin(string Origin, double? QuotaSize = default)    
    {
      return new Enyim.Iris.Protocol.Storage.OverrideQuotaForOriginRequest(Origin, QuotaSize);
    }
    /// <summary>Override quota for the specified origin</summary>
    /// <param name="Origin">Security origin.</param>
    /// <param name="QuotaSize">
    /// The quota size (in bytes) to override the original quota with.<br/>
    /// If this is called multiple times, the overridden quota will be equal to<br/>
    /// the quotaSize provided in the final call. If this is called without<br/>
    /// specifying a quotaSize, the quota will be reset to the default value for<br/>
    /// the specified origin. If this is called multiple times with different<br/>
    /// origins, the override will be maintained for each origin until it is<br/>
    /// disabled (called without a quotaSize).<br/>
    /// </param>
    [ChromeProtocol.Core.MethodName("Storage.overrideQuotaForOrigin")]
    public record OverrideQuotaForOriginRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("origin")]
      string Origin,
      [property: System.Text.Json.Serialization.JsonPropertyName("quotaSize")]
      double? QuotaSize = default
    ) : ChromeProtocol.Core.ICommand<OverrideQuotaForOriginRequestResult>
    {
    }
    public record OverrideQuotaForOriginRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Registers origin to be notified when an update occurs to its cache storage list.</summary>
    /// <param name="Origin">Security origin.</param>
    public static Enyim.Iris.Protocol.Storage.TrackCacheStorageForOriginRequest TrackCacheStorageForOrigin(string Origin)    
    {
      return new Enyim.Iris.Protocol.Storage.TrackCacheStorageForOriginRequest(Origin);
    }
    /// <summary>Registers origin to be notified when an update occurs to its cache storage list.</summary>
    /// <param name="Origin">Security origin.</param>
    [ChromeProtocol.Core.MethodName("Storage.trackCacheStorageForOrigin")]
    public record TrackCacheStorageForOriginRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("origin")]
      string Origin
    ) : ChromeProtocol.Core.ICommand<TrackCacheStorageForOriginRequestResult>
    {
    }
    public record TrackCacheStorageForOriginRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Registers storage key to be notified when an update occurs to its cache storage list.</summary>
    /// <param name="StorageKey">Storage key.</param>
    public static Enyim.Iris.Protocol.Storage.TrackCacheStorageForStorageKeyRequest TrackCacheStorageForStorageKey(string StorageKey)    
    {
      return new Enyim.Iris.Protocol.Storage.TrackCacheStorageForStorageKeyRequest(StorageKey);
    }
    /// <summary>Registers storage key to be notified when an update occurs to its cache storage list.</summary>
    /// <param name="StorageKey">Storage key.</param>
    [ChromeProtocol.Core.MethodName("Storage.trackCacheStorageForStorageKey")]
    public record TrackCacheStorageForStorageKeyRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("storageKey")]
      string StorageKey
    ) : ChromeProtocol.Core.ICommand<TrackCacheStorageForStorageKeyRequestResult>
    {
    }
    public record TrackCacheStorageForStorageKeyRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Registers origin to be notified when an update occurs to its IndexedDB.</summary>
    /// <param name="Origin">Security origin.</param>
    public static Enyim.Iris.Protocol.Storage.TrackIndexedDBForOriginRequest TrackIndexedDBForOrigin(string Origin)    
    {
      return new Enyim.Iris.Protocol.Storage.TrackIndexedDBForOriginRequest(Origin);
    }
    /// <summary>Registers origin to be notified when an update occurs to its IndexedDB.</summary>
    /// <param name="Origin">Security origin.</param>
    [ChromeProtocol.Core.MethodName("Storage.trackIndexedDBForOrigin")]
    public record TrackIndexedDBForOriginRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("origin")]
      string Origin
    ) : ChromeProtocol.Core.ICommand<TrackIndexedDBForOriginRequestResult>
    {
    }
    public record TrackIndexedDBForOriginRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Registers storage key to be notified when an update occurs to its IndexedDB.</summary>
    /// <param name="StorageKey">Storage key.</param>
    public static Enyim.Iris.Protocol.Storage.TrackIndexedDBForStorageKeyRequest TrackIndexedDBForStorageKey(string StorageKey)    
    {
      return new Enyim.Iris.Protocol.Storage.TrackIndexedDBForStorageKeyRequest(StorageKey);
    }
    /// <summary>Registers storage key to be notified when an update occurs to its IndexedDB.</summary>
    /// <param name="StorageKey">Storage key.</param>
    [ChromeProtocol.Core.MethodName("Storage.trackIndexedDBForStorageKey")]
    public record TrackIndexedDBForStorageKeyRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("storageKey")]
      string StorageKey
    ) : ChromeProtocol.Core.ICommand<TrackIndexedDBForStorageKeyRequestResult>
    {
    }
    public record TrackIndexedDBForStorageKeyRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Unregisters origin from receiving notifications for cache storage.</summary>
    /// <param name="Origin">Security origin.</param>
    public static Enyim.Iris.Protocol.Storage.UntrackCacheStorageForOriginRequest UntrackCacheStorageForOrigin(string Origin)    
    {
      return new Enyim.Iris.Protocol.Storage.UntrackCacheStorageForOriginRequest(Origin);
    }
    /// <summary>Unregisters origin from receiving notifications for cache storage.</summary>
    /// <param name="Origin">Security origin.</param>
    [ChromeProtocol.Core.MethodName("Storage.untrackCacheStorageForOrigin")]
    public record UntrackCacheStorageForOriginRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("origin")]
      string Origin
    ) : ChromeProtocol.Core.ICommand<UntrackCacheStorageForOriginRequestResult>
    {
    }
    public record UntrackCacheStorageForOriginRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Unregisters storage key from receiving notifications for cache storage.</summary>
    /// <param name="StorageKey">Storage key.</param>
    public static Enyim.Iris.Protocol.Storage.UntrackCacheStorageForStorageKeyRequest UntrackCacheStorageForStorageKey(string StorageKey)    
    {
      return new Enyim.Iris.Protocol.Storage.UntrackCacheStorageForStorageKeyRequest(StorageKey);
    }
    /// <summary>Unregisters storage key from receiving notifications for cache storage.</summary>
    /// <param name="StorageKey">Storage key.</param>
    [ChromeProtocol.Core.MethodName("Storage.untrackCacheStorageForStorageKey")]
    public record UntrackCacheStorageForStorageKeyRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("storageKey")]
      string StorageKey
    ) : ChromeProtocol.Core.ICommand<UntrackCacheStorageForStorageKeyRequestResult>
    {
    }
    public record UntrackCacheStorageForStorageKeyRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Unregisters origin from receiving notifications for IndexedDB.</summary>
    /// <param name="Origin">Security origin.</param>
    public static Enyim.Iris.Protocol.Storage.UntrackIndexedDBForOriginRequest UntrackIndexedDBForOrigin(string Origin)    
    {
      return new Enyim.Iris.Protocol.Storage.UntrackIndexedDBForOriginRequest(Origin);
    }
    /// <summary>Unregisters origin from receiving notifications for IndexedDB.</summary>
    /// <param name="Origin">Security origin.</param>
    [ChromeProtocol.Core.MethodName("Storage.untrackIndexedDBForOrigin")]
    public record UntrackIndexedDBForOriginRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("origin")]
      string Origin
    ) : ChromeProtocol.Core.ICommand<UntrackIndexedDBForOriginRequestResult>
    {
    }
    public record UntrackIndexedDBForOriginRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Unregisters storage key from receiving notifications for IndexedDB.</summary>
    /// <param name="StorageKey">Storage key.</param>
    public static Enyim.Iris.Protocol.Storage.UntrackIndexedDBForStorageKeyRequest UntrackIndexedDBForStorageKey(string StorageKey)    
    {
      return new Enyim.Iris.Protocol.Storage.UntrackIndexedDBForStorageKeyRequest(StorageKey);
    }
    /// <summary>Unregisters storage key from receiving notifications for IndexedDB.</summary>
    /// <param name="StorageKey">Storage key.</param>
    [ChromeProtocol.Core.MethodName("Storage.untrackIndexedDBForStorageKey")]
    public record UntrackIndexedDBForStorageKeyRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("storageKey")]
      string StorageKey
    ) : ChromeProtocol.Core.ICommand<UntrackIndexedDBForStorageKeyRequestResult>
    {
    }
    public record UntrackIndexedDBForStorageKeyRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Returns the number of stored Trust Tokens per issuer for the<br/>
    /// current browsing context.<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.Storage.GetTrustTokensRequest GetTrustTokens()    
    {
      return new Enyim.Iris.Protocol.Storage.GetTrustTokensRequest();
    }
    /// <summary>
    /// Returns the number of stored Trust Tokens per issuer for the<br/>
    /// current browsing context.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("Storage.getTrustTokens")]
    public record GetTrustTokensRequest() : ChromeProtocol.Core.ICommand<GetTrustTokensRequestResult>
    {
    }
    public record GetTrustTokensRequestResult(
      [property: System.Text.Json.Serialization.JsonPropertyName("tokens")]
      System.Collections.Generic.IReadOnlyList<Enyim.Iris.Protocol.Storage.TrustTokensType> Tokens
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Removes all Trust Tokens issued by the provided issuerOrigin.<br/>
    /// Leaves other stored data, including the issuer&#39;s Redemption Records, intact.<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.Storage.ClearTrustTokensRequest ClearTrustTokens(string IssuerOrigin)    
    {
      return new Enyim.Iris.Protocol.Storage.ClearTrustTokensRequest(IssuerOrigin);
    }
    /// <summary>
    /// Removes all Trust Tokens issued by the provided issuerOrigin.<br/>
    /// Leaves other stored data, including the issuer&#39;s Redemption Records, intact.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("Storage.clearTrustTokens")]
    public record ClearTrustTokensRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("issuerOrigin")]
      string IssuerOrigin
    ) : ChromeProtocol.Core.ICommand<ClearTrustTokensRequestResult>
    {
    }
    /// <param name="DidDeleteTokens">True if any tokens were deleted, false otherwise.</param>
    public record ClearTrustTokensRequestResult(
      [property: System.Text.Json.Serialization.JsonPropertyName("didDeleteTokens")]
      bool DidDeleteTokens
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Gets details for a named interest group.</summary>
    public static Enyim.Iris.Protocol.Storage.GetInterestGroupDetailsRequest GetInterestGroupDetails(string OwnerOrigin, string Name)    
    {
      return new Enyim.Iris.Protocol.Storage.GetInterestGroupDetailsRequest(OwnerOrigin, Name);
    }
    /// <summary>Gets details for a named interest group.</summary>
    [ChromeProtocol.Core.MethodName("Storage.getInterestGroupDetails")]
    public record GetInterestGroupDetailsRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("ownerOrigin")]
      string OwnerOrigin,
      [property: System.Text.Json.Serialization.JsonPropertyName("name")]
      string Name
    ) : ChromeProtocol.Core.ICommand<GetInterestGroupDetailsRequestResult>
    {
    }
    /// <param name="Details">
    /// This largely corresponds to:<br/>
    /// https://wicg.github.io/turtledove/#dictdef-generatebidinterestgroup<br/>
    /// but has absolute expirationTime instead of relative lifetimeMs and<br/>
    /// also adds joiningOrigin.<br/>
    /// </param>
    public record GetInterestGroupDetailsRequestResult(
      [property: System.Text.Json.Serialization.JsonPropertyName("details")]
      System.Text.Json.Nodes.JsonObject Details
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Enables/Disables issuing of interestGroupAccessed events.</summary>
    public static Enyim.Iris.Protocol.Storage.SetInterestGroupTrackingRequest SetInterestGroupTracking(bool Enable)    
    {
      return new Enyim.Iris.Protocol.Storage.SetInterestGroupTrackingRequest(Enable);
    }
    /// <summary>Enables/Disables issuing of interestGroupAccessed events.</summary>
    [ChromeProtocol.Core.MethodName("Storage.setInterestGroupTracking")]
    public record SetInterestGroupTrackingRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("enable")]
      bool Enable
    ) : ChromeProtocol.Core.ICommand<SetInterestGroupTrackingRequestResult>
    {
    }
    public record SetInterestGroupTrackingRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Enables/Disables issuing of interestGroupAuctionEventOccurred and<br/>
    /// interestGroupAuctionNetworkRequestCreated.<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.Storage.SetInterestGroupAuctionTrackingRequest SetInterestGroupAuctionTracking(bool Enable)    
    {
      return new Enyim.Iris.Protocol.Storage.SetInterestGroupAuctionTrackingRequest(Enable);
    }
    /// <summary>
    /// Enables/Disables issuing of interestGroupAuctionEventOccurred and<br/>
    /// interestGroupAuctionNetworkRequestCreated.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("Storage.setInterestGroupAuctionTracking")]
    public record SetInterestGroupAuctionTrackingRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("enable")]
      bool Enable
    ) : ChromeProtocol.Core.ICommand<SetInterestGroupAuctionTrackingRequestResult>
    {
    }
    public record SetInterestGroupAuctionTrackingRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Gets metadata for an origin&#39;s shared storage.</summary>
    public static Enyim.Iris.Protocol.Storage.GetSharedStorageMetadataRequest GetSharedStorageMetadata(string OwnerOrigin)    
    {
      return new Enyim.Iris.Protocol.Storage.GetSharedStorageMetadataRequest(OwnerOrigin);
    }
    /// <summary>Gets metadata for an origin&#39;s shared storage.</summary>
    [ChromeProtocol.Core.MethodName("Storage.getSharedStorageMetadata")]
    public record GetSharedStorageMetadataRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("ownerOrigin")]
      string OwnerOrigin
    ) : ChromeProtocol.Core.ICommand<GetSharedStorageMetadataRequestResult>
    {
    }
    public record GetSharedStorageMetadataRequestResult(
      [property: System.Text.Json.Serialization.JsonPropertyName("metadata")]
      Enyim.Iris.Protocol.Storage.SharedStorageMetadataType Metadata
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Gets the entries in an given origin&#39;s shared storage.</summary>
    public static Enyim.Iris.Protocol.Storage.GetSharedStorageEntriesRequest GetSharedStorageEntries(string OwnerOrigin)    
    {
      return new Enyim.Iris.Protocol.Storage.GetSharedStorageEntriesRequest(OwnerOrigin);
    }
    /// <summary>Gets the entries in an given origin&#39;s shared storage.</summary>
    [ChromeProtocol.Core.MethodName("Storage.getSharedStorageEntries")]
    public record GetSharedStorageEntriesRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("ownerOrigin")]
      string OwnerOrigin
    ) : ChromeProtocol.Core.ICommand<GetSharedStorageEntriesRequestResult>
    {
    }
    public record GetSharedStorageEntriesRequestResult(
      [property: System.Text.Json.Serialization.JsonPropertyName("entries")]
      System.Collections.Generic.IReadOnlyList<Enyim.Iris.Protocol.Storage.SharedStorageEntryType> Entries
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Sets entry with `key` and `value` for a given origin&#39;s shared storage.</summary>
    /// <param name="IgnoreIfPresent">
    /// If `ignoreIfPresent` is included and true, then only sets the entry if<br/>
    /// `key` doesn&#39;t already exist.<br/>
    /// </param>
    public static Enyim.Iris.Protocol.Storage.SetSharedStorageEntryRequest SetSharedStorageEntry(string OwnerOrigin, string Key, string Value, bool? IgnoreIfPresent = default)    
    {
      return new Enyim.Iris.Protocol.Storage.SetSharedStorageEntryRequest(OwnerOrigin, Key, Value, IgnoreIfPresent);
    }
    /// <summary>Sets entry with `key` and `value` for a given origin&#39;s shared storage.</summary>
    /// <param name="IgnoreIfPresent">
    /// If `ignoreIfPresent` is included and true, then only sets the entry if<br/>
    /// `key` doesn&#39;t already exist.<br/>
    /// </param>
    [ChromeProtocol.Core.MethodName("Storage.setSharedStorageEntry")]
    public record SetSharedStorageEntryRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("ownerOrigin")]
      string OwnerOrigin,
      [property: System.Text.Json.Serialization.JsonPropertyName("key")]
      string Key,
      [property: System.Text.Json.Serialization.JsonPropertyName("value")]
      string Value,
      [property: System.Text.Json.Serialization.JsonPropertyName("ignoreIfPresent")]
      bool? IgnoreIfPresent = default
    ) : ChromeProtocol.Core.ICommand<SetSharedStorageEntryRequestResult>
    {
    }
    public record SetSharedStorageEntryRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Deletes entry for `key` (if it exists) for a given origin&#39;s shared storage.</summary>
    public static Enyim.Iris.Protocol.Storage.DeleteSharedStorageEntryRequest DeleteSharedStorageEntry(string OwnerOrigin, string Key)    
    {
      return new Enyim.Iris.Protocol.Storage.DeleteSharedStorageEntryRequest(OwnerOrigin, Key);
    }
    /// <summary>Deletes entry for `key` (if it exists) for a given origin&#39;s shared storage.</summary>
    [ChromeProtocol.Core.MethodName("Storage.deleteSharedStorageEntry")]
    public record DeleteSharedStorageEntryRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("ownerOrigin")]
      string OwnerOrigin,
      [property: System.Text.Json.Serialization.JsonPropertyName("key")]
      string Key
    ) : ChromeProtocol.Core.ICommand<DeleteSharedStorageEntryRequestResult>
    {
    }
    public record DeleteSharedStorageEntryRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Clears all entries for a given origin&#39;s shared storage.</summary>
    public static Enyim.Iris.Protocol.Storage.ClearSharedStorageEntriesRequest ClearSharedStorageEntries(string OwnerOrigin)    
    {
      return new Enyim.Iris.Protocol.Storage.ClearSharedStorageEntriesRequest(OwnerOrigin);
    }
    /// <summary>Clears all entries for a given origin&#39;s shared storage.</summary>
    [ChromeProtocol.Core.MethodName("Storage.clearSharedStorageEntries")]
    public record ClearSharedStorageEntriesRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("ownerOrigin")]
      string OwnerOrigin
    ) : ChromeProtocol.Core.ICommand<ClearSharedStorageEntriesRequestResult>
    {
    }
    public record ClearSharedStorageEntriesRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Resets the budget for `ownerOrigin` by clearing all budget withdrawals.</summary>
    public static Enyim.Iris.Protocol.Storage.ResetSharedStorageBudgetRequest ResetSharedStorageBudget(string OwnerOrigin)    
    {
      return new Enyim.Iris.Protocol.Storage.ResetSharedStorageBudgetRequest(OwnerOrigin);
    }
    /// <summary>Resets the budget for `ownerOrigin` by clearing all budget withdrawals.</summary>
    [ChromeProtocol.Core.MethodName("Storage.resetSharedStorageBudget")]
    public record ResetSharedStorageBudgetRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("ownerOrigin")]
      string OwnerOrigin
    ) : ChromeProtocol.Core.ICommand<ResetSharedStorageBudgetRequestResult>
    {
    }
    public record ResetSharedStorageBudgetRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Enables/disables issuing of sharedStorageAccessed events.</summary>
    public static Enyim.Iris.Protocol.Storage.SetSharedStorageTrackingRequest SetSharedStorageTracking(bool Enable)    
    {
      return new Enyim.Iris.Protocol.Storage.SetSharedStorageTrackingRequest(Enable);
    }
    /// <summary>Enables/disables issuing of sharedStorageAccessed events.</summary>
    [ChromeProtocol.Core.MethodName("Storage.setSharedStorageTracking")]
    public record SetSharedStorageTrackingRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("enable")]
      bool Enable
    ) : ChromeProtocol.Core.ICommand<SetSharedStorageTrackingRequestResult>
    {
    }
    public record SetSharedStorageTrackingRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Set tracking for a storage key&#39;s buckets.</summary>
    public static Enyim.Iris.Protocol.Storage.SetStorageBucketTrackingRequest SetStorageBucketTracking(string StorageKey, bool Enable)    
    {
      return new Enyim.Iris.Protocol.Storage.SetStorageBucketTrackingRequest(StorageKey, Enable);
    }
    /// <summary>Set tracking for a storage key&#39;s buckets.</summary>
    [ChromeProtocol.Core.MethodName("Storage.setStorageBucketTracking")]
    public record SetStorageBucketTrackingRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("storageKey")]
      string StorageKey,
      [property: System.Text.Json.Serialization.JsonPropertyName("enable")]
      bool Enable
    ) : ChromeProtocol.Core.ICommand<SetStorageBucketTrackingRequestResult>
    {
    }
    public record SetStorageBucketTrackingRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Deletes the Storage Bucket with the given storage key and bucket name.</summary>
    public static Enyim.Iris.Protocol.Storage.DeleteStorageBucketRequest DeleteStorageBucket(Enyim.Iris.Protocol.Storage.StorageBucketType Bucket)    
    {
      return new Enyim.Iris.Protocol.Storage.DeleteStorageBucketRequest(Bucket);
    }
    /// <summary>Deletes the Storage Bucket with the given storage key and bucket name.</summary>
    [ChromeProtocol.Core.MethodName("Storage.deleteStorageBucket")]
    public record DeleteStorageBucketRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("bucket")]
      Enyim.Iris.Protocol.Storage.StorageBucketType Bucket
    ) : ChromeProtocol.Core.ICommand<DeleteStorageBucketRequestResult>
    {
    }
    public record DeleteStorageBucketRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Deletes state for sites identified as potential bounce trackers, immediately.</summary>
    public static Enyim.Iris.Protocol.Storage.RunBounceTrackingMitigationsRequest RunBounceTrackingMitigations()    
    {
      return new Enyim.Iris.Protocol.Storage.RunBounceTrackingMitigationsRequest();
    }
    /// <summary>Deletes state for sites identified as potential bounce trackers, immediately.</summary>
    [ChromeProtocol.Core.MethodName("Storage.runBounceTrackingMitigations")]
    public record RunBounceTrackingMitigationsRequest() : ChromeProtocol.Core.ICommand<RunBounceTrackingMitigationsRequestResult>
    {
    }
    public record RunBounceTrackingMitigationsRequestResult(
      [property: System.Text.Json.Serialization.JsonPropertyName("deletedSites")]
      System.Collections.Generic.IReadOnlyList<string> DeletedSites
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>
    /// Returns the effective Related Website Sets in use by this profile for the browser<br/>
    /// session. The effective Related Website Sets will not change during a browser session.<br/>
    /// </summary>
    public static Enyim.Iris.Protocol.Storage.GetRelatedWebsiteSetsRequest GetRelatedWebsiteSets()    
    {
      return new Enyim.Iris.Protocol.Storage.GetRelatedWebsiteSetsRequest();
    }
    /// <summary>
    /// Returns the effective Related Website Sets in use by this profile for the browser<br/>
    /// session. The effective Related Website Sets will not change during a browser session.<br/>
    /// </summary>
    [ChromeProtocol.Core.MethodName("Storage.getRelatedWebsiteSets")]
    public record GetRelatedWebsiteSetsRequest() : ChromeProtocol.Core.ICommand<GetRelatedWebsiteSetsRequestResult>
    {
    }
    public record GetRelatedWebsiteSetsRequestResult(
      [property: System.Text.Json.Serialization.JsonPropertyName("sets")]
      System.Collections.Generic.IReadOnlyList<Enyim.Iris.Protocol.Storage.RelatedWebsiteSetType> Sets
    ) : ChromeProtocol.Core.IType
    {
    }
    public static Enyim.Iris.Protocol.Storage.SetProtectedAudienceKAnonymityRequest SetProtectedAudienceKAnonymity(string Owner, string Name, System.Collections.Generic.IReadOnlyList<string> Hashes)    
    {
      return new Enyim.Iris.Protocol.Storage.SetProtectedAudienceKAnonymityRequest(Owner, Name, Hashes);
    }
    [ChromeProtocol.Core.MethodName("Storage.setProtectedAudienceKAnonymity")]
    public record SetProtectedAudienceKAnonymityRequest(
      [property: System.Text.Json.Serialization.JsonPropertyName("owner")]
      string Owner,
      [property: System.Text.Json.Serialization.JsonPropertyName("name")]
      string Name,
      [property: System.Text.Json.Serialization.JsonPropertyName("hashes")]
      System.Collections.Generic.IReadOnlyList<string> Hashes
    ) : ChromeProtocol.Core.ICommand<SetProtectedAudienceKAnonymityRequestResult>
    {
    }
    public record SetProtectedAudienceKAnonymityRequestResult() : ChromeProtocol.Core.IType
    {
    }
  }
}
